package auttoken

import (
	"github.com/abesuite/abec/ctaut/script"
)

// AutToken holds the information of token in memory, and would be used to conduct the RULE-CHECKS.
type AutToken struct {
	// AutToken's version inherits the version of the script which creates the AutToken.
	Version uint32

	// HostOutPoint is used to track the host location on blockchain, say host-Txo.
	HostOutPoint script.HostOutPoint

	// CoinAddress means the address on chain that a coin belongs to,
	// say, each coin on chain has a format (coinAddress, valueScript).
	// Do not limit the CoinAddress here to the concept in CryptoAddress in abecryptox package.
	// As Abelian-Txo belongs to CoinAddress, AutToken also belongs to CoinAddress.
	// For all token, coinAdress would be used to indicate the ownership of token
	// For root token, it would be used match the claimed issuers to recognize operational permission.
	CoinAddress []byte

	// ValueScript stores the value information for the AutToken.
	// For AutRootToken, valueScript would be nil,
	// For normal AutToken, valueScript is set by the OUTER LAYER,
	// and at present, it is set to be the serializedAutTxo, which is generated by the underlying crypto-scheme.
	ValueScript []byte
}
