package abecryptox

import (
	"github.com/abesuite/abec/wire"
)

// AbeTxOutputDesc defines the description for Txo generation.
// reviewed on 2023.12.07
type AbeTxOutputDesc struct {
	cryptoAddress []byte // generated by CryptoAddressKeyGen
	value         uint64
}

// NewAbeTxOutDesc constructs a new AbeTxOutputDesc from the input (cryptoAddress []byte, value uint64).
// reviewed on 2023.12.07
func NewAbeTxOutDesc(cryptoAddress []byte, value uint64) *AbeTxOutputDesc {
	return &AbeTxOutputDesc{
		cryptoAddress: cryptoAddress,
		value:         value,
	}
}

//func (abeTxOutputDesc *AbeTxOutputDesc) GetValue() uint64 {
//	return abeTxOutputDesc.value
//}

// AbeTxInputDesc defines the data that are need to spend a TxoCoin, in TransferTxGen.
// reviewed on 2023.12.21
type AbeTxInputDesc struct {
	// ringId        *wire.RingId  // txoRing identifier
	txoRing       *wire.TxoRing // complete TxoRing information
	sidx          uint8         // spend which one
	cryptoAddress []byte        // address, generated by CryptoAddressKeyGen
	cryptoSpsk    []byte        // spend secret key, generated by CryptoAddressKeyGen
	cryptoSnsk    []byte        //  serial-number secret key, generated by CryptoAddressKeyGen
	cryptoVsk     []byte        //  view secret key, generated by CryptoAddressKeyGen
	value         uint64
}

// NewAbeTxInputDesc constructs a new AbeTxInputDesc.
// reviewed on 2023.12.21
func NewAbeTxInputDesc( //ringId *wire.RingId,
	txoRing *wire.TxoRing,
	sidx uint8, cryptoAddress []byte, cryptoSpsk []byte, cryptoSnsk []byte, cryptoVsk []byte, value uint64) *AbeTxInputDesc {
	return &AbeTxInputDesc{
		//ringId:        ringId,
		txoRing:       txoRing,
		sidx:          sidx,
		cryptoAddress: cryptoAddress,
		cryptoSpsk:    cryptoSpsk,
		cryptoSnsk:    cryptoSnsk,
		cryptoVsk:     cryptoVsk,
		value:         value,
	}
}

// AbeTxInDetail defines the data describing a consumed TxoCoin in TransferTx, which will be used in TransferTxVerify
// reviewed on 2023.12.21
type AbeTxInDetail struct {
	ringId       wire.RingId // txoRing identifier
	txoList      []*wire.TxOutAbe
	serialNumber []byte
}

// NewAbeTxInDetail constructs a new NewAbeTxInDetail.
// reviewed on 2023.12.21
func NewAbeTxInDetail(ringId wire.RingId, txoList []*wire.TxOutAbe, serialNumber []byte) *AbeTxInDetail {
	return &AbeTxInDetail{
		ringId:       ringId,
		txoList:      txoList,
		serialNumber: serialNumber,
	}
}

//	data structures for abec side	end
