package abecryptox

import (
	"github.com/abesuite/abec/ctaut"
)

// AbeTxOutputDesc defines the description for Txo generation.
type AutTxOutputDesc struct {
	autTxoType         AutTxoType
	value              uint64
	coinValuePublicKey []byte // generated by CryptoAddressKeyGen
}

func (autTxOutputDesc *AutTxOutputDesc) AutTxoType() AutTxoType {
	return autTxOutputDesc.autTxoType
}

func (autTxOutputDesc *AutTxOutputDesc) Value() uint64 {
	return autTxOutputDesc.value
}

func (autTxOutputDesc *AutTxOutputDesc) CoinValuePublicKey() []byte {
	return autTxOutputDesc.coinValuePublicKey
}

// NewAbeTxOutDesc constructs a new AbeTxOutputDesc from the input (cryptoAddress []byte, value uint64).
func NewAutTxOutDesc(autTxoType AutTxoType, value uint64, coinValuePublicKey []byte) *AutTxOutputDesc {
	return &AutTxOutputDesc{
		autTxoType:         autTxoType,
		value:              value,
		coinValuePublicKey: coinValuePublicKey,
	}
}

// AbeTxInputDescByRootSeeds defines the information that will be need to spend a TxoCoin, in TransferTxGen.
// The information consists of Root Seeds and coinDetectorRootKey.
// NOTE: The (Root Seeds, Root Key) should be those used to generate the cryptoAddress.
// NOTE: As cryptoAddress=cryptoScheme+privacyLevel+coinAddress, these coinXXXRootSeeds is purely randomness, without containing cryptoScheme or privacyLevel,
// this is because, generating these (Root Seeds, Root Key) is the responsibility of the caller of abecrypto.
// AbeTxInputDesc defines the data that are need to spend a TxoCoin, in TransferTxGen.
type AutTxInputDesc struct {
	autTxo             *ctaut.AutTxo // complete TxoRing information
	coinValuePublicKey []byte        //  view secret key, generated by CryptoAddressKeyGen; for Pseudonym-Privacy coin, this should be nil
	coinValueSecretKey []byte        //  view secret key, generated by CryptoAddressKeyGen; for Pseudonym-Privacy coin, this should be nil
	value              uint64
}

// NewAbeTxInputDescByKeys constructs a new NewAbeTxInputDescByKeys.
func NewAutTxInputDesc(autTxo *ctaut.AutTxo,
	coinValuePublicKey []byte, coinValueSecretKey []byte, value uint64) *AutTxInputDesc {
	return &AutTxInputDesc{
		autTxo:             autTxo,
		coinValuePublicKey: coinValuePublicKey,
		coinValueSecretKey: coinValueSecretKey,
		value:              value,
	}
}

//	data structures for abec side	end
