package abecryptox

import (
	"github.com/abesuite/abec/chainhash"
	"github.com/abesuite/abec/wire"
)

// AbeTxOutputDesc defines the description for Txo generation.
type AbeTxOutputDesc struct {
	cryptoAddress []byte // generated by CryptoAddressKeyGen
	value         uint64
}

func NewAbeTxOutDesc(cryptoAddress []byte, value uint64) *AbeTxOutputDesc {
	return &AbeTxOutputDesc{
		cryptoAddress: cryptoAddress,
		value:         value,
	}
}

func (abeTxOutputDesc *AbeTxOutputDesc) GetValue() uint64 {
	return abeTxOutputDesc.value
}

// AbeTxInDetail defines the data describing a consumed TxoCoin in TransferTx, which will be used in TransferTxVerify
type AbeTxInDetail struct {
	ringHash     chainhash.Hash // txoRing identifier
	txoList      []*wire.TxOutAbe
	serialNumber []byte
}

func NewAbeTxInDetail(ringHash chainhash.Hash, txoList []*wire.TxOutAbe, serialNumber []byte) *AbeTxInDetail {
	return &AbeTxInDetail{
		ringHash:     ringHash,
		txoList:      txoList,
		serialNumber: serialNumber,
	}
}

//	data structures for abec side	end
