package abecryptox

import (
	"github.com/pqabelian/abec/ctaut/wire"
)

// AutTxOutputDesc defines the description for AuxTxo generation.
// ctx review done 2025.12.21
type AutTxOutputDesc struct {
	autTxoType         AutTxoType
	value              uint64
	coinValuePublicKey []byte // generated by CryptoAddressKeyGen
}

// AutTxoType
// ctx review done 2025.12.21
func (autTxOutputDesc *AutTxOutputDesc) AutTxoType() AutTxoType {
	return autTxOutputDesc.autTxoType
}

// Value
// ctx review done 2025.12.21
func (autTxOutputDesc *AutTxOutputDesc) Value() uint64 {
	return autTxOutputDesc.value
}

// CoinValuePublicKey
// ctx review done 2025.12.21
func (autTxOutputDesc *AutTxOutputDesc) CoinValuePublicKey() []byte {
	return autTxOutputDesc.coinValuePublicKey
}

// NewAutTxOutDesc constructs a new AutTxOutputDesc.
// ctx review done 2025.12.21
func NewAutTxOutDesc(autTxoType AutTxoType, value uint64, coinValuePublicKey []byte) *AutTxOutputDesc {
	return &AutTxOutputDesc{
		autTxoType:         autTxoType,
		value:              value,
		coinValuePublicKey: coinValuePublicKey,
	}
}

// AutTxInputDesc defines the information that will be need to spend a AutTxo, in AutTransferTxGen.
// As AutTransferTx handles only the value balance, here only (coinValuePublicKey,coinValueSecretKey) pair is included.
// ctx review done 2025.12.21
type AutTxInputDesc struct {
	autTxo             *wire.AutTxo // AutTxo to be spent
	coinValuePublicKey []byte       // view secret key, generated by CryptoAddressKeyGen; for Pseudonym-Privacy coin, this should be nil
	coinValueSecretKey []byte       // view secret key, generated by CryptoAddressKeyGen; for Pseudonym-Privacy coin, this should be nil
	value              uint64       // value
}

// NewAutTxInputDesc constructs a new AutTxInputDesc.
// ctx review done 2025.12.21
func NewAutTxInputDesc(autTxo *wire.AutTxo,
	coinValuePublicKey []byte, coinValueSecretKey []byte, value uint64) *AutTxInputDesc {
	return &AutTxInputDesc{
		autTxo:             autTxo,
		coinValuePublicKey: coinValuePublicKey,
		coinValueSecretKey: coinValueSecretKey,
		value:              value,
	}
}

//	data structures for abec side	end

// ctx review done 2025.12.21
