package dao

import (
	"bytes"
	"encoding/hex"
	"io"

	"github.com/abesuite/abec/chainhash"
	"github.com/abesuite/abec/wire"
)

const MaxIssuerAddressLength = 256 // not exact, to have some redundancy

// HostOutPoint defines the host of aut token, it could be used to track previous tokens.
type HostOutPoint = wire.OutPointAbe

type AutId = chainhash.Hash

// AutIssuer defines Aut Issuer by IssuerAddress, where IssuerAddress is a wrapper of coinAddress.
// Each AutIssuer corresponds to a coinAddress,
// where coinAddress means the address on chain that a coin belongs to,
// say, each coin on chain has a format (coinAddress, valueScript).
// Do not limit the coinAddress here to the concept in CryptoAddress in abecryptox package.
// Note that, as Abelian-Txo belongs to coinAddress, AutToken also belongs to coinAddress.
// Note that it must keep that each AutIssuer can be identified by its underlying coinAddress.
// Note that it must keep that each AutIssuer can be identified by its IssuerAddress.
type AutIssuer struct {
	IssuerAddress []byte
}

//// NewAutIssuer returns a new AutIssuer for the input issuerAddress.
//// todo: at this moment, we have not define issuerAddress. The design is to allow suture extension.
//func NewAutIssuer(issuerAddress []byte) *AutIssuer {
//	return &AutIssuer{
//		IssuerAddress: issuerAddress,
//	}
//}

// NewAutIssuerFromCoinAddress creates an AutIssuer from the input coinAddress.
func NewAutIssuerFromCoinAddress(coinAddress []byte) *AutIssuer {
	// At this moment, IssuerAddress is exactly coinAddress.
	return &AutIssuer{
		IssuerAddress: coinAddress,
	}
}

// CoinAddress returns the coinAddress contained in autIssuer.IssuerAddress.
func (autIssuer *AutIssuer) CoinAddress() []byte {
	// At present, IssuerAddress is exactly the coinAddress.
	return autIssuer.IssuerAddress
}

func (autIssuer *AutIssuer) SerializeSize() int {
	return wire.VarIntSerializeSize(uint64(len(autIssuer.IssuerAddress))) + len(autIssuer.IssuerAddress)
}

func (autIssuer *AutIssuer) Write(w io.Writer) error {
	return wire.WriteVarBytes(w, 0, autIssuer.IssuerAddress)
}

func (autIssuer *AutIssuer) Read(r io.Reader) error {
	issuerAddress, err := wire.ReadVarBytes(r, 0, MaxIssuerAddressLength, "AutIssuer.IssuerAddress")
	if err != nil {
		return err
	}

	autIssuer.IssuerAddress = issuerAddress
	return nil
}

func (autIssuer *AutIssuer) String() string {
	return hex.EncodeToString(autIssuer.IssuerAddress)
}

// Equal reports whether autIssuer and issuer have the same IssuerAddress.
// Equal returns TURE only if
// autIssuer and issuer are not nil,
// autIssuer.IssuerAddress and issuer.IssuerAddress are not nil/empty, and
// autIssuer.IssuerAddress and issuer.IssuerAddress have the same length and contain the same bytes.
func (autIssuer *AutIssuer) Equal(issuer *AutIssuer) bool {
	if autIssuer == nil || issuer == nil {
		return false
	}

	if len(autIssuer.IssuerAddress) == 0 || len(issuer.IssuerAddress) == 0 {
		return false
	}

	return bytes.Equal(autIssuer.IssuerAddress, issuer.IssuerAddress)
}

func (autIssuer *AutIssuer) Clone() *AutIssuer {
	if autIssuer == nil {
		return nil
	}

	rst := &AutIssuer{}
	rst.IssuerAddress = make([]byte, len(autIssuer.IssuerAddress))
	copy(rst.IssuerAddress, autIssuer.IssuerAddress)
	return rst
}

// AutToken holds the information of token in memory, and would be used to conduct the RULE-CHECKS.
type AutToken struct {
	// AutToken's version inherits the version of the script which creates the AutToken.
	Version uint32

	// HostOutPoint is used to track the host location on blockchain, say host-Txo.
	HostOutPoint HostOutPoint

	// CoinAddress means the address on chain that a coin belongs to,
	// say, each coin on chain has a format (coinAddress, valueScript).
	// Do not limit the CoinAddress here to the concept in CryptoAddress in abecryptox package.
	// As Abelian-Txo belongs to CoinAddress, AutToken also belongs to CoinAddress.
	// For all token, coinAddress would be used to indicate the owner of a token.
	// For root token, it would be used match the claimed issuers to recognize operational permission.
	CoinAddress []byte

	// ValueScript stores the value information for the AutToken.
	// For AutRootToken, valueScript would be nil,
	// For normal AutToken, valueScript is set by the OUTER LAYER,
	// and at present, it is set to be the serializedAutTxo, which is generated by the underlying crypto-scheme.
	ValueScript []byte
}

// end of codes
