package ctaut

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"

	"github.com/abesuite/abec/abecryptox"
	"github.com/abesuite/abec/chainhash"
	ctautwire "github.com/abesuite/abec/ctaut/wire"
	"github.com/abesuite/abec/wire"
)

// HostOutPoint defines the host of aut token, it could be used to track previous tokens.
type HostOutPoint = wire.OutPoint

// Metadata maintains the metadata information of Abelian User Token (AUT) instance on Abelian
// 1. The identifier of AUT instance are UNIQUE
// 2. Each instance has its own name, symbol, and unit name
// 3. Each instance has its planned total issued amount
// 4. Each instance has issuers, each minting and updating is required to meet the preset threshold
// 5. Issuers are responsible for maintaining the metadata before the expired height.
//
// In details:
// RegistrationScript would register a new instance with unique CTAutIdentifier on Abelian, and generate some special
// tokens, named 'root token', that would be consumed by MintScript or ReRegistrationScript
//
// MintScript would be used to issue normal tokens (a.k.a token), and it would consume some root tokens in RootTokenSet,
// and also update the MintedAmount
//
// ReRegistrationScript would be used to update the metadata information, including fields PlannedTotalAmount /
// IssuerTokens / MintThreshold / ReregistrationThreshold / ExpireHeight
//
// # TransferScript would be used to transfer tokens between users, it would not affect any of the fields in Metadata
//
// BurnTx would be used to burn some tokens, it would not affect any of the fields in Metadata
type Metadata struct {
	// The TxHash of the host transaction (i.e. txid) where the registration script is located would be used as its instance identifier
	// identifiers for different instances are unique
	CTAutIdentifier [CTAUTIdentifierLength]byte
	// The name of token could be used to improve usability, but MUST NOT be assumed that the value must be present
	// The full, descriptive and human-readable name of the token
	// e.g. "Post-Quantum USD"
	CTAutName []byte
	// The symbol of token could be used to improve usability, but MUST NOT be assumed that the value must be present.
	// A short, human-readable string that acts as a ticker for the token.
	// e.g. "PQUSD"
	CTAutSymbol []byte
	// The name he commonly used units of tokens, could be used to user representation,
	// but MUST NOT be assumed that the value must be present
	// e.g. "USD"
	BaseUnitName []byte
	// The name of the token used for counting
	// but MUST NOT be assumed that the value must be present
	// e.g. "Cent"
	SubUnitName []byte
	// The scale between BaseUnit and SubUnit
	// e.g. 100
	UnitScale uint64
	// The memo for AUT instance
	CTAutMemo []byte

	// The total amount of token would be issued, this means total limit for all MintScript
	// Note that the amount would be counted in terms of subunit
	PlannedTotalAmount uint64
	// The issuers of CT-AUT instance, currently, identified by its coin address on Abelian
	IssuerTokens [][]byte
	// The number of different issuers in a MintScript must meet this threshold to make it valid
	MintThreshold uint8
	// The number of different issuers in a ReRegistrationScript must meet this threshold to make it valid
	ReregistrationThreshold uint8
	// The next ReRegistrationScript must be recorded before this height, otherwise the instance would not update anymore
	// TODO consider never expiring with -1?
	// TODO affect minting?
	ExpireHeight int32

	// The mined amount of token
	// TODO Consider recycling burned amount?
	// global GDP is USD $106 trillion in 2023 -> 47-byte
	MintedAmount uint64
	// The following fields hold the currently available root tokens, held by Issuers
	// generated by RegistrationScript or ReRegistrationScript and consumed by MintScript
	RootTokenSet map[HostOutPoint]struct{}
}

func (info *Metadata) SerializedSize() int {
	n :=
		/*identifier, actually fixed length */ wire.VarIntSerializeSize(uint64(len(info.CTAutIdentifier))) + len(info.CTAutIdentifier) +
			/* name, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutName))) + len(info.CTAutName) +
			/* symbol, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutSymbol))) + len(info.CTAutSymbol) +
			/* base unit, variable length */ wire.VarIntSerializeSize(uint64(len(info.BaseUnitName))) + len(info.BaseUnitName) +
			/* sub unit, variable length */ wire.VarIntSerializeSize(uint64(len(info.SubUnitName))) + len(info.SubUnitName) +
			/* scale, variable length */ wire.VarIntSerializeSize(info.UnitScale) +
			/* memo, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutMemo))) + len(info.CTAutMemo)

	n += /* planned amount */ wire.VarIntSerializeSize(info.PlannedTotalAmount)

	n += /* number of issuer tokens */ wire.VarIntSerializeSize(uint64(len(info.IssuerTokens)))
	for i := 0; i < len(info.IssuerTokens); i++ {
		/* actually fixed length */
		n += wire.VarIntSerializeSize(uint64(len(info.IssuerTokens[i]))) + len(info.IssuerTokens[i])
	}

	n +=
		/* update threshold */ 1 +
			/* issue threshold */ 1 +
			/* expire height */ wire.VarIntSerializeSize(uint64(info.ExpireHeight))

	n += /* minted amount,variable length */ wire.VarIntSerializeSize(info.MintedAmount) +
		/* number of issuer tokens */ wire.VarIntSerializeSize(uint64(len(info.RootTokenSet)))

	for point := range info.RootTokenSet {
		n += wire.VarIntSerializeSize(uint64(len(point.Hash))) + len(point.Hash)
		n += 1
	}
	for i := 0; i < len(info.RootTokenSet); i++ {
		/* actually fixed length */
		n += wire.VarIntSerializeSize(uint64(len(info.IssuerTokens[i]))) + len(info.IssuerTokens[i])
		n += 1
	}

	return n
}
func (info *Metadata) Serialize() ([]byte, error) {
	if info == nil {
		return nil, errors.New("nil pointer to Metadata for serialize")
	}
	// Calculate the size needed to serialize AUT info.
	var err error
	size := info.SerializedSize()
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	buff := bytes.NewBuffer(make([]byte, 0, size))
	if err = wire.WriteVarBytes(buff, 0, info.CTAutIdentifier[:]); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.CTAutName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(buff, 0, info.CTAutSymbol); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.BaseUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(buff, 0, info.SubUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarInt(buff, 0, info.UnitScale); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.CTAutMemo); err != nil {
		return nil, err
	}

	if err = wire.WriteVarInt(buff, 0, info.PlannedTotalAmount); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, uint64(len(info.IssuerTokens)))
	if err != nil {
		return nil, err
	}
	for i := 0; i < len(info.IssuerTokens); i++ {
		err = wire.WriteVarBytes(buff, 0, info.IssuerTokens[i])
		if err != nil {
			return nil, errors.New("error to write issuer token")
		}
	}

	if err = buff.WriteByte(info.ReregistrationThreshold); err != nil {
		return nil, err
	}
	if err = buff.WriteByte(info.MintThreshold); err != nil {
		return nil, err
	}
	if err = wire.WriteVarInt(buff, 0, uint64(info.ExpireHeight)); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, info.MintedAmount)
	if err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, uint64(len(info.RootTokenSet)))
	if err != nil {
		return nil, err
	}
	for point := range info.RootTokenSet {
		err = wire.WriteVarBytes(buff, 0, point.Hash[:])
		if err != nil {
			return nil, errors.New("error to write point")
		}
		err = buff.WriteByte(uint8(point.Index))
		if err != nil {
			return nil, errors.New("error to write point index")
		}
	}

	return buff.Bytes(), nil
}
func (info *Metadata) Deserialize(r io.Reader) error {
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	var err error
	identifier, err := wire.ReadVarBytes(r, 0, CTAUTIdentifierLength, "identifier")
	if err != nil {
		return err
	}
	// assert
	if len(identifier) != CTAUTIdentifierLength {
		return errors.New("unexpected identifier length")
	}
	copy(info.CTAutIdentifier[:], identifier)

	if info.CTAutName, err = wire.ReadVarBytes(r, 0, maxCTAUTNameLength, "name"); err != nil {
		return err
	}
	if info.CTAutSymbol, err = wire.ReadVarBytes(r, 0, maxCTAUTSymbolLength, "symbol"); err != nil {
		return err
	}
	if info.BaseUnitName, err = wire.ReadVarBytes(r, 0, maxBaseUnitLength, "unit"); err != nil {
		return err
	}
	if info.SubUnitName, err = wire.ReadVarBytes(r, 0, maxSubUnitLength, "subunit"); err != nil {
		return err
	}
	if info.UnitScale, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}
	if info.CTAutMemo, err = wire.ReadVarBytes(r, 0, maxCTAUTMemoLength, "memo"); err != nil {
		return err
	}

	if info.PlannedTotalAmount, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}

	issuerNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.IssuerTokens = make([][]byte, issuerNum)
	for i := uint64(0); i < issuerNum; i++ {
		info.IssuerTokens[i], err = wire.ReadVarBytes(r, 0, issuerTokenLength, "issuerToken")
		if err != nil {
			return errors.New("error to write issuer token")
		}
	}

	if info.ReregistrationThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if info.MintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	expiredHeight, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.ExpireHeight = int32(expiredHeight)

	info.MintedAmount, err = wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}

	rootCoinNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.RootTokenSet = make(map[HostOutPoint]struct{}, rootCoinNum)
	for i := uint64(0); i < issuerNum; i++ {
		txHashBytes, err := wire.ReadVarBytes(r, 0, chainhash.HashSize, "hash")
		if err != nil {
			return errors.New("error to write issuer token")
		}
		txHash, err := chainhash.NewHash(txHashBytes)
		if err != nil {
			return errors.New("invalid hash for ctaut point")
		}

		index, err := ReadByte(r)
		if err != nil {
			return err
		}
		point := HostOutPoint{
			Hash:  *txHash,
			Index: uint32(index),
		}
		info.RootTokenSet[point] = struct{}{}
	}

	return nil
}

// Clone returns a shallow copy of the utxo entry.
func (info *Metadata) Clone() *Metadata {
	if info == nil {
		return nil
	}

	// ToDo(Alice): by the same order as the definition?
	cloned := &Metadata{
		CTAutIdentifier: [CTAUTIdentifierLength]byte{},

		CTAutName:    make([]byte, len(info.CTAutName)),
		CTAutSymbol:  make([]byte, len(info.CTAutSymbol)),
		BaseUnitName: make([]byte, len(info.BaseUnitName)),
		SubUnitName:  make([]byte, len(info.SubUnitName)),
		UnitScale:    info.UnitScale,
		CTAutMemo:    make([]byte, len(info.CTAutMemo)),

		IssuerTokens:            make([][]byte, len(info.IssuerTokens)),
		ReregistrationThreshold: info.ReregistrationThreshold,
		MintThreshold:           info.MintThreshold,
		PlannedTotalAmount:      info.PlannedTotalAmount,
		ExpireHeight:            info.ExpireHeight,

		MintedAmount: info.MintedAmount,
		RootTokenSet: make(map[HostOutPoint]struct{}, len(info.RootTokenSet)),
	}

	copy(cloned.CTAutIdentifier[:], info.CTAutIdentifier[:])

	copy(cloned.CTAutSymbol, info.CTAutSymbol)
	copy(cloned.CTAutName, info.CTAutName)
	copy(cloned.BaseUnitName, info.BaseUnitName)
	copy(cloned.SubUnitName, info.SubUnitName)
	copy(cloned.CTAutMemo, info.CTAutMemo)

	for i := 0; i < len(info.IssuerTokens); i++ {
		cloned.IssuerTokens[i] = make([]byte, len(info.IssuerTokens[i]))
		copy(cloned.IssuerTokens[i][:], info.IssuerTokens[i][:])
	}

	for outpoint := range info.RootTokenSet {
		newOutpoint := HostOutPoint{}
		copy(newOutpoint.Hash[:], outpoint.Hash[:])
		newOutpoint.Index = outpoint.Index

		cloned.RootTokenSet[newOutpoint] = struct{}{}
	}

	return cloned
}

// todo(ctaut): this is for database storage or only memeory? why has CoinAddress and ValueScript?
// todo(ctaut): define an interface? only a case needs coinAddress.
// CTAUTToken holds the main information of token in memory, it would be used to check all rules
type CTAUTToken struct {
	// inheritance from host transaction
	Version uint32
	// used to track the host location on blockchain
	HostOutPoint HostOutPoint
	// For root token, value script would be nil,
	// For normal token, value script could be interpreted to either a public value or a hidden value
	// with abecryptox.ExtractAutTxoValue()
	ValueScript []byte // todo(ctaut): used to denote AUT value.
	// For all token, coin address would be used to indicate the ownership of token
	// For root token, it would be used match the claimed issuers to recognize operational permission
	CoinAddress []byte
}

type CTAUTScript interface {
	Type() CTAUTScriptType
	Identifier() [CTAUTIdentifierLength]byte
	Serialize() ([]byte, error)
	Deserialize(io.Reader) error

	setConsumedTokens([]*CTAUTToken) error
	ConsumedTokens() []*CTAUTToken

	setGeneratedTokens([]*CTAUTToken) error
	GeneratedTokens() []*CTAUTToken
}

// RegistrationScript would be the structured script parsed from memo in host transaction,
// 1. the metadata for the instance will be extracted from the script with RegistrationScript.Metadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// RegistrationScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "0"
// <Identifier> a byte array with fixed length TODO remove from script or reserved with zero-bytes?
// <AUTName> a byte array with max length, would not be changed anymore
// <AUSymbol> a byte array with max length, would not be changed anymore
// <baseUnitName> a byte array with max length, would not be changed anymore
// <subUnitName> a byte array with max length, would not be changed anymore
// <UnitScale> the scale between unit and minUnit, would not be changed anymore
// <ctAutMemo> a byte array with max length
//
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of generated RootTokens> A number n, explicitly mark the 0~(n-1)-th pseudonym TXO of this transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type RegistrationScript struct {
	// inheritance from transactions
	version    uint32
	scriptType CTAUTScriptType

	// populate with txid of host transaction
	ctAutIdentifier [CTAUTIdentifierLength]byte

	ctAutName    []byte
	ctAutSymbol  []byte
	baseUnitName []byte
	subUnitName  []byte
	unitScale    uint64
	ctAutMemo    []byte

	plannedTotalAmount  uint64
	issuerTokens        [][]byte
	mintThreshold       uint8
	reregisterThreshold uint8
	expireHeight        int32

	outAutRootTokenNum uint8 // value is set in deserialize, so, do not provide set function, but provide get function.
	// TODO: just append to the script?
	memo []byte

	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *RegistrationScript) Type() CTAUTScriptType {
	return script.scriptType
}
func (script *RegistrationScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *RegistrationScript) Serialize() ([]byte, error) {
	// todo(ctaut): initialize a space first?
	// w := bytes.NewBuffer(make([]byte,script.SerializeSize()))
	var b bytes.Buffer
	var err error

	if err = writePrefix(b, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutSymbol); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.baseUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.subUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, script.unitScale); err != nil {
		return nil, err
	}
	if err = writeAutMemo(b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}
	if err = writeIssuerTokens(b, script.issuerTokens); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, uint64(script.expireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}
	if err = writeMemo(b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *RegistrationScript) Deserialize(r io.Reader) error {
	var err error

	if script.ctAutIdentifier, err = readPrefix(r, Registration); err != nil {
		return err
	}
	if script.ctAutName, err = ReadVarBytes(r, maxCTAUTNameLength, "name"); err != nil {
		return err
	}
	if script.ctAutSymbol, err = ReadVarBytes(r, maxCTAUTSymbolLength, "symbol"); err != nil {
		return err
	}
	if script.baseUnitName, err = ReadVarBytes(r, maxBaseUnitLength, "baseUnit"); err != nil {
		return err
	}
	if script.subUnitName, err = ReadVarBytes(r, maxSubUnitLength, "subUnit"); err != nil {
		return err
	}
	if script.unitScale, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}
	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	script.expireHeight = int32(expireHeight)

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	return script.SanityCheck()
}

func (script *RegistrationScript) SanityCheck() error {
	if script.scriptType != Registration {
		return errors.New("unexpected type for registration script")
	}

	if !bytes.Equal(script.ctAutIdentifier[:], zeroIdentifier[:]) {
		return ErrInValidAUTTx
	}
	if len(script.ctAutName) == 0 || len(script.ctAutName) > maxCTAUTNameLength {
		return ErrInValidAUTTx
	}
	if len(script.ctAutSymbol) == 0 || len(script.ctAutSymbol) > maxCTAUTSymbolLength {
		return ErrInValidAUTTx
	}

	if len(script.baseUnitName) == 0 || len(script.baseUnitName) > maxBaseUnitLength {
		return ErrInValidAUTTx
	}
	if len(script.subUnitName) == 0 || len(script.subUnitName) > maxSubUnitLength {
		return ErrInValidAUTTx
	}
	if script.unitScale == 0 || script.unitScale > maxAmount || script.unitScale > script.plannedTotalAmount {
		return ErrInValidAUTTx
	}
	if len(script.ctAutMemo) > maxCTAUTMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > maxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > maxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.expireHeight <= 0 || script.expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > maxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *RegistrationScript) ConsumedTokens() []*CTAUTToken {
	return script.consumedTokens
}
func (script *RegistrationScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != 0 {
		return errors.New("mismatched number of consumed tokens")
	}
	script.consumedTokens = consumedTokens
	return nil
}

func (script *RegistrationScript) GeneratedTokens() []*CTAUTToken {
	return script.generatedTokens
}
func (script *RegistrationScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != int(script.outAutRootTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.generatedTokens = generatedTokens
	return nil
}
func (script *RegistrationScript) ExpireHeight() int32 {
	return script.expireHeight
}

func (script *RegistrationScript) Metadata() *Metadata {
	rootTokenSet := map[HostOutPoint]struct{}{}
	for i := 0; i < len(script.generatedTokens); i++ {
		rootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}
	return &Metadata{
		CTAutIdentifier:         script.ctAutIdentifier,
		CTAutName:               script.ctAutName,
		CTAutSymbol:             script.ctAutSymbol,
		BaseUnitName:            script.baseUnitName,
		SubUnitName:             script.subUnitName,
		UnitScale:               script.unitScale,
		CTAutMemo:               script.ctAutMemo,
		PlannedTotalAmount:      script.plannedTotalAmount,
		IssuerTokens:            script.issuerTokens,
		MintThreshold:           script.mintThreshold,
		ReregistrationThreshold: script.reregisterThreshold,
		ExpireHeight:            script.expireHeight,

		MintedAmount: 0,
		RootTokenSet: rootTokenSet,
	}
}

var _ CTAUTScript = &RegistrationScript{}

// ReRegistrationScript would be the structured script parsed from memo in host transaction,
// 1. The field values used to update the metadata will be extracted from the scripts with ReRegistrationScript.UpdateMetadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// ReRegistrationScript would be serialized with following format
// Flag = "CTAUTReRegistration"
// <Common Prefix> "CTAUTSCRIPT" "1"
// <Identifier> a byte array with fixed length, would not be changed anymore
// <AUTMemo> a byte array with max length
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of consumed RootTokens> A number m, explicitly specify the 0~(m-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of generated RootTokens> A number n, Explicitly specify the 0~(n-1)-th pseudonym TXO of outputs in host transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type ReRegistrationScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	ctAutMemo []byte

	plannedTotalAmount  uint64
	issuerTokens        [][]byte
	mintThreshold       uint8
	reregisterThreshold uint8
	expireHeight        int32

	inAutRootTokenNum  uint8
	outAutRootTokenNum uint8
	// TODO: just append to the script?
	memo []byte

	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *ReRegistrationScript) PlannedTotalAmount() uint64 {
	return script.plannedTotalAmount
}

func (script *ReRegistrationScript) ExpireHeight() int32 {
	return script.expireHeight
}

func (script *ReRegistrationScript) Type() CTAUTScriptType {
	return ReRegistration
}

func (script *ReRegistrationScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *ReRegistrationScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	if err = writePrefix(b, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = writeAutMemo(b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}

	if err = writeIssuerTokens(b, script.issuerTokens); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, uint64(script.expireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}

	if err = writeMemo(b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *ReRegistrationScript) Deserialize(r io.Reader) error {
	var err error

	if script.ctAutIdentifier, err = readPrefix(r, ReRegistration); err != nil {
		return err
	}

	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}

	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}

	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	if expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}
	script.expireHeight = int32(expireHeight)

	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	if err = script.SanityCheck(); err != nil {
		return nil
	}

	return nil
}
func (script *ReRegistrationScript) SanityCheck() error {
	if script.scriptType != ReRegistration {
		return errors.New("unexpected type for re-registration script")
	}

	if len(script.ctAutMemo) > maxCTAUTMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > maxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > maxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.expireHeight <= 0 || script.expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.inAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > maxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *ReRegistrationScript) ConsumedTokens() []*CTAUTToken {
	return script.consumedTokens
}
func (script *ReRegistrationScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != int(script.inAutRootTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.consumedTokens = consumedTokens
	return nil
}
func (script *ReRegistrationScript) GeneratedTokens() []*CTAUTToken {
	return script.generatedTokens
}
func (script *ReRegistrationScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != int(script.outAutRootTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.generatedTokens = generatedTokens
	return nil
}

func (script *ReRegistrationScript) UpdateMetadata(metadata *Metadata) error {
	// assert
	if !bytes.Equal(script.ctAutIdentifier[:], metadata.CTAutIdentifier[:]) {
		return ErrInValidAUTTx
	}
	consumedTokens := script.consumedTokens
	for i := 0; i < len(consumedTokens); i++ {
		if _, ok := metadata.RootTokenSet[consumedTokens[i].HostOutPoint]; !ok {
			return fmt.Errorf("an re-registration AUT transaction try to update AUT "+
				"with non-existing/spent root token (%s,%d) for AUT identified by %s",
				consumedTokens[i].HostOutPoint.Hash, consumedTokens[i].HostOutPoint.Index,
				metadata.CTAutIdentifier)
		}
		delete(metadata.RootTokenSet, consumedTokens[i].HostOutPoint)
	}

	metadata.CTAutMemo = script.ctAutMemo
	// assert here?
	if metadata.MintedAmount > script.plannedTotalAmount {
		return errors.New("re-registration transaction try to make planned amount less than minted amount")
	}
	metadata.PlannedTotalAmount = script.plannedTotalAmount

	metadata.IssuerTokens = script.issuerTokens
	metadata.MintThreshold = script.mintThreshold
	metadata.ReregistrationThreshold = script.reregisterThreshold
	metadata.ExpireHeight = script.expireHeight

	// remove previous root tokens
	metadata.RootTokenSet = make(map[HostOutPoint]struct{}, len(script.generatedTokens))
	for i := 0; i < len(script.generatedTokens); i++ {
		metadata.RootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}

	return nil
}

var _ CTAUTScript = &ReRegistrationScript{}

// MintScript would be the structured script parsed from memo in host transaction,
// 1. the minted amount with such a script MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// MintScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "2"
// <Identifier> a byte array with fixed length
// <Vin> an integer, representing the amount of token to be minted, must less than plannedTotalAmount
// <Number of RootToken> A number n, explicitly specify the 0~(n-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type MintScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	vin                 uint64
	inAutRootTokenNum   uint8
	outCTAutTokenNum    uint8 // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	outPlainAutTokenNum uint8 // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	valueScripts        [][]byte
	witnessHash         chainhash.Hash // todo(ctaut): move to the last position
	memo                []byte

	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *MintScript) Vin() uint64 {
	return script.vin
}

func (script *MintScript) Type() CTAUTScriptType {
	return script.scriptType
}
func (script *MintScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *MintScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	if err = writePrefix(b, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.vin); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}
	if err = writeCTAUTTxoScripts(b, script.valueScripts); err != nil {
		return nil, err
	}
	if err = writeWitnessHash(b, script.witnessHash); err != nil {
		return nil, err
	}
	if err = writeMemo(b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil

}
func (script *MintScript) Deserialize(r io.Reader) error {
	var err error

	if script.ctAutIdentifier, err = readPrefix(r, Mint); err != nil {
		return err
	}

	if script.vin, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}

func (script *MintScript) SanityCheck() error {
	if script.scriptType != Mint {
		return errors.New("unexpected type for mint script")
	}

	if script.vin == 0 || script.vin > maxAmount {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > maxNumCTToken {
		return ErrInValidAUTTx
	}
	if int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) > maxNumToken {
		return ErrInValidAUTTx
	}

	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}
	for i := 0; i < len(script.valueScripts); i++ {
		autTxoType, err := abecryptox.GetAutTxoType(&ctautwire.AutTxo{
			Version:   script.version,
			TxoScript: script.valueScripts[i],
		})
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > maxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}
func (script *MintScript) ConsumedTokens() []*CTAUTToken {
	return script.consumedTokens
}
func (script *MintScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != int(script.inAutRootTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.consumedTokens = consumedTokens
	return nil
}
func (script *MintScript) GeneratedTokens() []*CTAUTToken {
	return script.generatedTokens
}
func (script *MintScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.generatedTokens = generatedTokens
	return nil
}

var _ CTAUTScript = &MintScript{}

// TransferScript would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// TransferScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "3"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type TransferScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	inCTAutTokenNum    uint8
	inPlainAutTokenNum uint8

	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	autTxoScripts       [][]byte

	witnessHash chainhash.Hash
	memo        []byte

	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *TransferScript) Type() CTAUTScriptType {
	return script.scriptType
}

func (script *TransferScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *TransferScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	if err = writePrefix(b, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}
	if err = writeCTAUTTxoScripts(b, script.autTxoScripts); err != nil {
		return nil, err
	}

	if err = writeWitnessHash(b, script.witnessHash); err != nil {
		return nil, err
	}
	if err = writeMemo(b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *TransferScript) Deserialize(r io.Reader) error {
	var err error
	if script.ctAutIdentifier, err = readPrefix(r, Transfer); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.autTxoScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	if err = script.SanityCheck(); err != nil {
		return err
	}
	return nil
}

func (script *TransferScript) SanityCheck() error {
	if script.scriptType != Transfer {
		return errors.New("unexpected type for transfer script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > maxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.autTxoScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.autTxoScripts); i++ {
		autTxoType, err := abecryptox.GetAutTxoType(&ctautwire.AutTxo{
			Version:   script.version,
			TxoScript: script.autTxoScripts[i],
		})
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > maxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *TransferScript) ConsumedTokens() []*CTAUTToken {
	return script.consumedTokens
}
func (script *TransferScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != int(script.inCTAutTokenNum)+int(script.inPlainAutTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.consumedTokens = consumedTokens
	return nil
}
func (script *TransferScript) GeneratedTokens() []*CTAUTToken {
	return script.generatedTokens
}
func (script *TransferScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.generatedTokens = generatedTokens
	return nil
}

var _ CTAUTScript = &TransferScript{}

// BurnTx would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts, and the first token would be marked burned TODO: MUST be Plain-Token?
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// BurnTx would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "3"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type BurnTx struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	inCTAutTokenNum     uint8
	inPlainAutTokenNum  uint8
	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	valueScripts        [][]byte

	witnessHash chainhash.Hash
	memo        []byte

	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *BurnTx) Type() CTAUTScriptType {
	return script.scriptType
}

func (script *BurnTx) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *BurnTx) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	if err = writePrefix(b, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}
	if err = writeCTAUTTxoScripts(b, script.valueScripts); err != nil {
		return nil, err
	}

	if err = writeWitnessHash(b, script.witnessHash); err != nil {
		return nil, err
	}
	if err = writeMemo(b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

// todo(ctaut): add a standalone sanity-check function, and call it at the end of deserialize
func (script *BurnTx) Deserialize(r io.Reader) error {
	var err error
	if script.ctAutIdentifier, err = readPrefix(r, Burn); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}
func (script *BurnTx) SanityCheck() error {
	if script.scriptType != Burn {
		return errors.New("unexpected type for burn script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > maxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.valueScripts); i++ {
		autTxoType, err := abecryptox.GetAutTxoType(&ctautwire.AutTxo{
			Version:   script.version,
			TxoScript: script.valueScripts[i],
		})
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > maxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *BurnTx) ConsumedTokens() []*CTAUTToken {
	return script.consumedTokens
}
func (script *BurnTx) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != int(script.inCTAutTokenNum)+int(script.inPlainAutTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.consumedTokens = consumedTokens
	return nil
}
func (script *BurnTx) GeneratedTokens() []*CTAUTToken {
	return script.generatedTokens
}
func (script *BurnTx) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return errors.New("mismatched number of consumed tokens")
	}
	script.generatedTokens = generatedTokens
	return nil
}

var _ CTAUTScript = &BurnTx{}

var ErrNonAutTx = errors.New("not a AUT transaction")
var ErrInValidAUTTx = errors.New("not a valid AUT transaction")

func getNumConsumedTokens(autTx CTAUTScript) (int, error) {
	switch autTransaction := autTx.(type) {
	case *RegistrationScript:
		return 0, nil
	case *ReRegistrationScript:
		return int(autTransaction.inAutRootTokenNum), nil
	case *MintScript:
		return int(autTransaction.inAutRootTokenNum), nil
	case *TransferScript:
		return int(autTransaction.inCTAutTokenNum + autTransaction.inPlainAutTokenNum), nil
	case *BurnTx:
		return int(autTransaction.inCTAutTokenNum + autTransaction.inPlainAutTokenNum), nil
	default:
		return 0, errors.New("unkown aut transaction type")
	}
}
func getNumGeneratedTokens(autTx CTAUTScript) (int, error) {
	switch autTransaction := autTx.(type) {
	case *RegistrationScript:
		return int(autTransaction.outAutRootTokenNum), nil
	case *ReRegistrationScript:
		return int(autTransaction.outAutRootTokenNum), nil
	case *MintScript:
		return int(autTransaction.outCTAutTokenNum + autTransaction.outPlainAutTokenNum), nil
	case *TransferScript:
		return int(autTransaction.outCTAutTokenNum + autTransaction.outPlainAutTokenNum), nil
	case *BurnTx:
		return int(autTransaction.outCTAutTokenNum + autTransaction.outPlainAutTokenNum), nil
	default:
		return 0, errors.New("unkown aut transaction type")
	}
}

// ExtractCTAUTScript try to deserialize CTAUT script from transaction memo
// if success, it would :
// - populate the consumed tokens by CTAUT script by populateConsumedTokens
// - populate the generated tokens by CTAUT script by populateGeneratedTokens
// - do sanity-check for AUT transaction, including
//   - no duplicate token is consumed in script
//   - no token parasitized in invalid type coin
//   - no conflict configuration found
//
// Note that the token legality and configuration rationalization MUST be checked with the help of instance on blockchain.
// - no double spending token
// - no overflow
func ExtractCTAUTScript(tx *wire.MsgTxAbe, lookupHostTxo func(ringHash chainhash.Hash) (*wire.TxOutAbe, error)) (autScript CTAUTScript, err error) {
	// could not be an AUT transaction
	if len(tx.TxMemo) < len(commonPrefix) {
		return nil, nil
	}
	if !bytes.Equal(tx.TxMemo[:len(commonPrefix)], []byte(commonPrefix)) {
		return nil, nil
	}

	if len(tx.TxMemo) == len(commonPrefix) {
		return nil, fmt.Errorf("the memo start with %s, but have no content", commonPrefix)
	}

	// todo(ctaut): why +1? "CTAUTSCRIPT" will result (nil, nil) or (nil, err)
	// todo(ctaut): only if ctaut-script's CommonPrefixLength is the the start position, it will be recognized as ctaut-script.
	// todo(ctaut): what "txMemo" should be shown at the front end?

	// inherit version from host transaction
	switch tx.TxMemo[len(commonPrefix)] {
	case Registration:
		autScript = &RegistrationScript{
			version: tx.Version,
		}
	case Mint:
		autScript = &MintScript{
			version: tx.Version,
		}
	case ReRegistration:
		autScript = &ReRegistrationScript{
			version: tx.Version,
		}
	case Transfer:
		autScript = &TransferScript{
			version: tx.Version,
		}
	case Burn:
		autScript = &BurnTx{
			version: tx.Version,
		}
	default:
		return nil, ErrInValidAUTTx
	}
	reader := bytes.NewBuffer(tx.TxMemo)
	err = autScript.Deserialize(reader)
	if err != nil {
		return nil, err
	}

	err = populateGeneratedCTAUTTokens(autScript, tx)
	if err != nil {
		return nil, err
	}

	err = populateConsumedCTAUTTokens(autScript, tx, lookupHostTxo)
	if err != nil {
		return nil, err
	}

	txHash := tx.TxHash()
	switch script := autScript.(type) {
	case *RegistrationScript:
		copy(script.ctAutIdentifier[:], txHash[:])
		// for inputs, there is no rules

		// for outputs, the claimed issuer tokens must match the generated tokens exactly
		// - all issuer tokens must appear
		// - No unclaimed issuer token appear
		if err = matchIssuerTokens(script.issuerTokens, script.generatedTokens); err != nil {
			return nil, err
		}
	case *ReRegistrationScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the re-register threshold is meet
		// Above checks have to be delayed until the instance could be seen

		// for outputs, the claimed issuer tokens must match the outputs exactly
		if err = matchIssuerTokens(script.issuerTokens, script.generatedTokens); err != nil {
			return nil, err
		}
	case *MintScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the mint threshold is meet
		// 3. check the minted amount conflict with planned total amount
		// Above checks have to be delayed until the instance could be seen

		witnessHash := chainhash.HashH(tx.AutWitness)
		if !witnessHash.IsEqual(&script.witnessHash) {
			return nil, fmt.Errorf("mismatch witness for script")
		}

		cbTx := &ctautwire.AutCoinbaseTx{
			Version:   script.version,
			Vin:       script.vin,
			TxOuts:    make([]*ctautwire.AutTxo, len(script.generatedTokens)),
			TxWitness: tx.AutWitness,
		}

		// for outputs, fill out the script
		version := tx.Version
		for i := 0; i < len(script.generatedTokens); i++ {
			cbTx.TxOuts[i] = &ctautwire.AutTxo{
				Version:   version,
				TxoScript: script.generatedTokens[i].ValueScript,
			}
		}

		err = abecryptox.AutCoinbaseTxVerify(cbTx)
		if err != nil {
			return nil, fmt.Errorf("transaction %s try to mint but the witness verfied fail with %s",
				txHash, err)
		}

	case *TransferScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the mint threshold is meet
		// 3. check the minted amount conflict with planned total amount
		// Above checks have to be delayed until the instance could be seen

		witnessHash := chainhash.HashH(tx.AutWitness)
		if !witnessHash.IsEqual(&script.witnessHash) {
			return nil, fmt.Errorf("mismatch witness for script")
		}

		trTx := &ctautwire.AutTransferTx{
			Version:   script.version,
			TxIns:     make([]*ctautwire.AutTxo, 0, len(script.consumedTokens)),
			TxOuts:    make([]*ctautwire.AutTxo, 0, len(script.generatedTokens)),
			TxWitness: tx.AutWitness,
		}

		for i := 0; i < len(script.consumedTokens); i++ {
			trTx.TxIns = append(trTx.TxIns, &ctautwire.AutTxo{
				Version:   script.consumedTokens[i].Version,
				TxoScript: script.consumedTokens[i].ValueScript,
			})
		}

		for i := 0; i < len(script.generatedTokens); i++ {
			trTx.TxOuts = append(trTx.TxOuts, &ctautwire.AutTxo{
				Version:   script.generatedTokens[i].Version,
				TxoScript: script.generatedTokens[i].ValueScript,
			})
		}

		err = abecryptox.AutTransferTxVerify(trTx)
		if err != nil {
			return nil, fmt.Errorf(`transaction %s try to transfer tokens but the witness verfied fail with %s`,
				txHash, err)
		}

	case *BurnTx:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the mint threshold is meet
		// 3. check the minted amount conflict with planned total amount
		// Above checks have to be delayed until the instance could be seen

		witnessHash := chainhash.HashH(tx.AutWitness)
		if !witnessHash.IsEqual(&script.witnessHash) {
			return nil, fmt.Errorf("mismatch witness for script")
		}

		trTx := &ctautwire.AutTransferTx{
			Version:   script.version,
			TxIns:     make([]*ctautwire.AutTxo, 0, len(script.consumedTokens)),
			TxOuts:    make([]*ctautwire.AutTxo, 0, len(script.generatedTokens)),
			TxWitness: tx.AutWitness,
		}

		for i := 0; i < len(script.consumedTokens); i++ {
			trTx.TxIns = append(trTx.TxIns, &ctautwire.AutTxo{
				Version:   script.consumedTokens[i].Version,
				TxoScript: script.consumedTokens[i].ValueScript,
			})
		}

		for i := 0; i < len(script.generatedTokens); i++ {
			trTx.TxOuts = append(trTx.TxOuts, &ctautwire.AutTxo{
				Version:   script.generatedTokens[i].Version,
				TxoScript: script.generatedTokens[i].ValueScript,
			})
		}

		err = abecryptox.AutTransferTxVerify(trTx)
		if err != nil {
			return nil, fmt.Errorf(`transaction %s try to transfer tokens but the witness verfied fail with %s`,
				txHash, err)
		}

	default:
		return nil, ErrInValidAUTTx
	}

	return autScript, nil
}
