package ctaut

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"reflect"

	"github.com/abesuite/abec/abecryptox"
	"github.com/abesuite/abec/abecryptox/abecryptoxkey"
	"github.com/abesuite/abec/chainhash"
	ctautwire "github.com/abesuite/abec/ctaut/wire"
	"github.com/abesuite/abec/wire"
)

// HostOutPoint defines the host of aut token, it could be used to track previous tokens.
type HostOutPoint = wire.OutPointAbe

// Metadata maintains the metadata information of Abelian User Token (AUT) instance on Abelian
// 1. The identifier of AUT instance are UNIQUE
// 2. Each instance has its own name, symbol, and unit name
// 3. Each instance has its planned total issued amount
// 4. Each instance has issuers, each minting and updating is required to meet the preset threshold
// 5. Issuers are responsible for maintaining the metadata before the expired height.
//
// In details:
// RegistrationScript would register a new instance with unique CTAutIdentifier on Abelian, and generate some special
// tokens, named 'root token', that would be consumed by MintScript or ReRegistrationScript
//
// MintScript would be used to issue normal tokens (a.k.a token), and it would consume some root tokens in RootTokenSet,
// and also update the MintedAmount
//
// ReRegistrationScript would be used to update the metadata information, including fields PlannedTotalSupply /
// IssuerTokens / MintThreshold / ReregistrationThreshold / ExpireHeight
//
// # TransferScript would be used to transfer tokens between users, it would not affect any of the fields in Metadata
//
// BurnScript would be used to burn some tokens, it would not affect any of the fields in Metadata
// todo: discuss use AutXXX, rather than CTAut ? affect too much?
// todo: rename to AutMetadata?
type AutMetadata struct {
	Version uint32
	// The TxHash of the host transaction (i.e. txid) where the registration script is located would be used as its instance identifier
	// identifiers for different instances are unique
	CTAutIdentifier chainhash.Hash // use chainhash.Hash directly
	// The name of token could be used to improve usability, but MUST NOT be assumed that the value must be present
	// The full, descriptive and human-readable name of the token
	// e.g. "Post-Quantum USD"
	CTAutName []byte
	// The symbol of token could be used to improve usability, but MUST NOT be assumed that the value must be present.
	// A short, human-readable string that acts as a ticker for the token.
	// e.g. "PQUSD"
	CTAutSymbol []byte
	// The name he commonly used units of tokens, could be used to user representation,
	// but MUST NOT be assumed that the value must be present
	// e.g. "USD"
	BaseUnitName []byte
	// The name of the token used for counting
	// but MUST NOT be assumed that the value must be present
	// e.g. "Cent"
	SubUnitName []byte
	// The scale between BaseUnit and SubUnit
	// e.g. 100
	UnitScale uint64
	// The memo for AUT instance
	CTAutMemo []byte

	// The total amount of token would be issued, this means total limit for all MintScript
	// Note that the amount would be counted in terms of subunit
	PlannedTotalSupply uint64
	// The issuers of CT-AUT instance, currently, identified by its coin address on Abelian
	IssuerTokens [][]byte
	// The number of different issuers in a MintScript must meet this threshold to make it valid
	MintThreshold uint8
	// The number of different issuers in a ReRegistrationScript must meet this threshold to make it valid
	ReregistrationThreshold uint8
	// The next ReRegistrationScript must be recorded before this height, otherwise the instance would not update anymore
	// TODO consider never expiring with -1(confirmed: use const)?
	ExpireHeight int32 // ExpireHeight -> ReregistrationExpireHeight

	// The minted amount of token
	MintedAmount uint64
	// The burned amount of token
	BurnedAmount uint64 // TODO add this field and logic
	// The following fields hold the currently available root tokens, held by Issuers
	// generated by RegistrationScript or ReRegistrationScript and consumed by MintScript
	// todo: is good to use HostOutPoint as the key?
	RootTokenSet map[HostOutPoint]struct{}
}

// todo: if only used locally, define as not-exported
func (info *AutMetadata) SerializedSize() int {
	n :=
		/*version, fixed length */ wire.VarIntSerializeSize(uint64(info.Version)) +
			/*identifier, actually fixed length */ wire.VarIntSerializeSize(uint64(len(info.CTAutIdentifier))) + len(info.CTAutIdentifier) +
			/* name, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutName))) + len(info.CTAutName) +
			/* symbol, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutSymbol))) + len(info.CTAutSymbol) +
			/* base unit, variable length */ wire.VarIntSerializeSize(uint64(len(info.BaseUnitName))) + len(info.BaseUnitName) +
			/* sub unit, variable length */ wire.VarIntSerializeSize(uint64(len(info.SubUnitName))) + len(info.SubUnitName) +
			/* scale, variable length */ wire.VarIntSerializeSize(info.UnitScale) +
			/* memo, variable length */ wire.VarIntSerializeSize(uint64(len(info.CTAutMemo))) + len(info.CTAutMemo)

	n += /* planned amount */ wire.VarIntSerializeSize(info.PlannedTotalSupply)

	n += /* number of issuer tokens */ wire.VarIntSerializeSize(uint64(len(info.IssuerTokens)))
	for i := 0; i < len(info.IssuerTokens); i++ {
		/* actually fixed length */
		n += wire.VarIntSerializeSize(uint64(len(info.IssuerTokens[i]))) + len(info.IssuerTokens[i])
	}

	n +=
		/* update threshold */ 1 +
			/* issue threshold */ 1 +
			/* expire height */ wire.VarIntSerializeSize(uint64(info.ExpireHeight))

	n += /* minted amount,variable length */ wire.VarIntSerializeSize(info.MintedAmount) +
		/* minted amount,variable length */ wire.VarIntSerializeSize(info.BurnedAmount) +
		/* number of issuer tokens */ wire.VarIntSerializeSize(uint64(len(info.RootTokenSet)))

	for point := range info.RootTokenSet {
		// todo: why use the key rather than the value?
		// todo: call HostOutPoint's serialize size, which use a fixed bytes for Hash
		// todo: the name should give clear meanings
		n += wire.VarIntSerializeSize(uint64(len(point.TxHash))) + len(point.TxHash)
		n += 1
	}
	for i := 0; i < len(info.IssuerTokens); i++ {
		/* actually fixed length */
		n += wire.VarIntSerializeSize(uint64(len(info.IssuerTokens[i]))) + len(info.IssuerTokens[i])
		n += 1
	}

	return n
}

// call abec.wire.WriteVarInt or call locally WriteVarInt?
func (info *AutMetadata) Serialize() ([]byte, error) {
	if info == nil {
		return nil, nil
	}
	// Calculate the size needed to serialize AUT info.
	var err error
	size := info.SerializedSize()
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	buff := bytes.NewBuffer(make([]byte, 0, size))
	if err = wire.WriteVarInt(buff, 0, uint64(info.Version)); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(buff, 0, info.CTAutIdentifier[:]); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.CTAutName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(buff, 0, info.CTAutSymbol); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.BaseUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(buff, 0, info.SubUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarInt(buff, 0, info.UnitScale); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(buff, 0, info.CTAutMemo); err != nil {
		return nil, err
	}

	if err = wire.WriteVarInt(buff, 0, info.PlannedTotalSupply); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, uint64(len(info.IssuerTokens)))
	if err != nil {
		return nil, err
	}
	for i := 0; i < len(info.IssuerTokens); i++ {
		err = wire.WriteVarBytes(buff, 0, info.IssuerTokens[i])
		if err != nil {
			return nil, errors.New("error to write issuer token")
		}
	}

	if err = buff.WriteByte(info.ReregistrationThreshold); err != nil {
		return nil, err
	}
	if err = buff.WriteByte(info.MintThreshold); err != nil {
		return nil, err
	}
	if err = wire.WriteVarInt(buff, 0, uint64(info.ExpireHeight)); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, info.MintedAmount)
	if err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, info.BurnedAmount)
	if err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(buff, 0, uint64(len(info.RootTokenSet)))
	if err != nil {
		return nil, err
	}
	for point := range info.RootTokenSet {
		// todo: use fix length buff.Write(), and package it
		err = wire.WriteVarBytes(buff, 0, point.TxHash[:])
		if err != nil {
			return nil, errors.New("error to write point")
		}
		err = buff.WriteByte(uint8(point.Index))
		if err != nil {
			return nil, errors.New("error to write point index")
		}
	}

	serializedMetadata := buff.Bytes()

	// todo: the following codes are necessary or only for test?
	tmpMetadata := &AutMetadata{}
	err = tmpMetadata.Deserialize(bytes.NewReader(serializedMetadata))
	if err != nil {
		return nil, err
	}
	if !reflect.DeepEqual(info, tmpMetadata) {
		return nil, errors.New("metadata not match after serialization")
	}

	return serializedMetadata, nil
}
func (info *AutMetadata) Deserialize(r io.Reader) error {
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	var err error
	version, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	// todo: need some check? whether version is in the expected scope
	info.Version = uint32(version)

	identifier, err := wire.ReadVarBytes(r, 0, CTAUTIdentifierLength, "identifier")
	if err != nil {
		return err
	}
	// assert
	if len(identifier) != CTAUTIdentifierLength {
		return errors.New("unexpected identifier length")
	}
	copy(info.CTAutIdentifier[:], identifier)

	if info.CTAutName, err = wire.ReadVarBytes(r, 0, MaxCTAUTNameLength, "name"); err != nil {
		return err
	}
	if info.CTAutSymbol, err = wire.ReadVarBytes(r, 0, MaxCTAUTSymbolLength, "symbol"); err != nil {
		return err
	}
	if info.BaseUnitName, err = wire.ReadVarBytes(r, 0, MaxBaseUnitLength, "unit"); err != nil {
		return err
	}
	if info.SubUnitName, err = wire.ReadVarBytes(r, 0, MaxSubUnitLength, "subunit"); err != nil {
		return err
	}
	if info.UnitScale, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}
	if info.CTAutMemo, err = wire.ReadVarBytes(r, 0, MaxCTAUTMemoLength, "memo"); err != nil {
		return err
	}

	if info.PlannedTotalSupply, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}

	issuerNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.IssuerTokens = make([][]byte, issuerNum)
	for i := uint64(0); i < issuerNum; i++ {
		info.IssuerTokens[i], err = wire.ReadVarBytes(r, 0, issuerTokenLength, "issuerToken")
		if err != nil {
			return errors.New("error to write issuer token")
		}
	}

	if info.ReregistrationThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if info.MintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	expiredHeight, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.ExpireHeight = int32(expiredHeight)

	info.MintedAmount, err = wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.BurnedAmount, err = wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}

	rootCoinNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	info.RootTokenSet = make(map[HostOutPoint]struct{}, rootCoinNum)
	for i := uint64(0); i < rootCoinNum; i++ {
		txHashBytes, err := wire.ReadVarBytes(r, 0, chainhash.HashSize, "hash")
		if err != nil {
			return errors.New("error to write issuer token")
		}
		txHash, err := chainhash.NewHash(txHashBytes)
		if err != nil {
			return errors.New("invalid hash for ctaut point")
		}

		index, err := ReadByte(r)
		if err != nil {
			return err
		}
		point := HostOutPoint{
			TxHash: *txHash,
			Index:  index,
		}
		info.RootTokenSet[point] = struct{}{}
	}

	return nil
}

// Clone returns a shallow copy of the utxo entry.
func (info *AutMetadata) Clone() *AutMetadata {
	if info == nil {
		return nil
	}

	// ToDo(Alice): by the same order as the definition?
	cloned := &AutMetadata{
		Version:         info.Version,
		CTAutIdentifier: [CTAUTIdentifierLength]byte{},

		CTAutName:    make([]byte, len(info.CTAutName)),
		CTAutSymbol:  make([]byte, len(info.CTAutSymbol)),
		BaseUnitName: make([]byte, len(info.BaseUnitName)),
		SubUnitName:  make([]byte, len(info.SubUnitName)),
		UnitScale:    info.UnitScale,
		CTAutMemo:    make([]byte, len(info.CTAutMemo)),

		IssuerTokens:            make([][]byte, len(info.IssuerTokens)),
		ReregistrationThreshold: info.ReregistrationThreshold,
		MintThreshold:           info.MintThreshold,
		PlannedTotalSupply:      info.PlannedTotalSupply,
		ExpireHeight:            info.ExpireHeight,

		MintedAmount: info.MintedAmount,
		BurnedAmount: info.BurnedAmount,
		RootTokenSet: make(map[HostOutPoint]struct{}, len(info.RootTokenSet)),
	}

	copy(cloned.CTAutIdentifier[:], info.CTAutIdentifier[:])

	copy(cloned.CTAutSymbol, info.CTAutSymbol)
	copy(cloned.CTAutName, info.CTAutName)
	copy(cloned.BaseUnitName, info.BaseUnitName)
	copy(cloned.SubUnitName, info.SubUnitName)
	copy(cloned.CTAutMemo, info.CTAutMemo)

	for i := 0; i < len(info.IssuerTokens); i++ {
		cloned.IssuerTokens[i] = make([]byte, len(info.IssuerTokens[i]))
		copy(cloned.IssuerTokens[i][:], info.IssuerTokens[i][:])
	}

	for outpoint := range info.RootTokenSet {
		newOutpoint := HostOutPoint{}
		copy(newOutpoint.TxHash[:], outpoint.TxHash[:])
		newOutpoint.Index = outpoint.Index

		cloned.RootTokenSet[newOutpoint] = struct{}{}
	}

	return cloned
}

// todo: AutScript?
// todo: as we add version control, could we modify the ScriptFlag to "AutScript"?
// todo: To implement an interface, implement the functions or methods?
type CTAUTScript interface {
	Version() uint32
	Type() CTAUTScriptType
	Identifier() [CTAUTIdentifierLength]byte

	Serialize() ([]byte, error)
	Deserialize(io.Reader) error // todo: make it to be symmetric? say, take []byte as input?

	NumConsumedTokens() int // todo: why not directly uint8? if leave it to be int, need to check when set this value.
	NumGeneratedTokens() int
}

// RegistrationScript would be the structured script parsed from memo in host transaction,
// 1. the metadata for the instance will be extracted from the script with RegistrationScript.Metadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// RegistrationScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "0"
// <Identifier> a byte array with fixed length TODO remove from script or reserved with zero-bytes?
// <AUTName> a byte array with max length, would not be changed anymore
// <AUSymbol> a byte array with max length, would not be changed anymore
// <baseUnitName> a byte array with max length, would not be changed anymore
// <subUnitName> a byte array with max length, would not be changed anymore
// <UnitScale> the scale between unit and minUnit, would not be changed anymore
// <ctAutMemo> a byte array with max length
//
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of generated RootTokens> A number n, explicitly mark the 0~(n-1)-th pseudonym TXO of this transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type RegistrationScript struct {
	// inheritance from transactions
	// todo: this version is ScriptVersion or the host-transaction's version?
	// todo: or named as ScriptVersion but inherit from and the same as host-transaction's version?
	// todo: consider has its own version field, but has a mapping to host-transaction's Version? this will give extension to the case
	// that the same tx's version may support different autScriptVersion.
	// // todo: if use the above design, the AutTxo.Version should use ScriptVersion, not the host-tx's version.
	version    uint32 // TODO(CTAUT) add version field in script self, check the usage version and the relation with the version in host transaction
	scriptType CTAUTScriptType

	// populate with txid of host transaction
	ctAutIdentifier [CTAUTIdentifierLength]byte

	ctAutName    []byte
	ctAutSymbol  []byte
	baseUnitName []byte
	subUnitName  []byte
	unitScale    uint64
	ctAutMemo    []byte

	plannedTotalAmount  uint64
	issuerTokens        [][]byte
	mintThreshold       uint8
	reregisterThreshold uint8
	expireHeight        int32

	outAutRootTokenNum uint8  // value is set in deserialize, so, do not provide set function, but provide get function.
	memo               []byte // todo: TODO memo -> scriptMemo
}

func (script *RegistrationScript) CtAutName() []byte {
	return script.ctAutName
}

func (script *RegistrationScript) CtAutSymbol() []byte {
	return script.ctAutSymbol
}

func (script *RegistrationScript) BaseUnitName() []byte {
	return script.baseUnitName
}

func (script *RegistrationScript) SubUnitName() []byte {
	return script.subUnitName
}

func (script *RegistrationScript) UnitScale() uint64 {
	return script.unitScale
}

func (script *RegistrationScript) CtAutMemo() []byte {
	return script.ctAutMemo
}

func (script *RegistrationScript) PlannedTotalAmount() uint64 {
	return script.plannedTotalAmount
}

func (script *RegistrationScript) IssuerTokens() [][]byte {
	return script.issuerTokens
}

func (script *RegistrationScript) MintThreshold() uint8 {
	return script.mintThreshold
}

func (script *RegistrationScript) ReregisterThreshold() uint8 {
	return script.reregisterThreshold
}

func (script *RegistrationScript) Memo() []byte {
	return script.memo
}

func NewRegistrationScript(
	version uint32,
	ctAutName []byte,
	ctAutSymbol []byte,
	baseUnitName []byte,
	subUnitName []byte,
	unitScale uint64,
	ctAutMemo []byte,
	plannedTotalAmount uint64,
	issuerTokens [][]byte,
	mintThreshold uint8,
	reregisterThreshold uint8,
	expireHeight int32,
	outAutRootTokenNum uint8,
	memo []byte,
) *RegistrationScript {
	return &RegistrationScript{
		version:             version,
		scriptType:          Registration,
		ctAutIdentifier:     [CTAUTIdentifierLength]byte{},
		ctAutName:           ctAutName,
		ctAutSymbol:         ctAutSymbol,
		baseUnitName:        baseUnitName,
		subUnitName:         subUnitName,
		unitScale:           unitScale,
		ctAutMemo:           ctAutMemo,
		plannedTotalAmount:  plannedTotalAmount,
		issuerTokens:        issuerTokens,
		mintThreshold:       mintThreshold,
		reregisterThreshold: reregisterThreshold,
		expireHeight:        expireHeight,
		outAutRootTokenNum:  outAutRootTokenNum,
		memo:                memo,
	}
}
func (script *RegistrationScript) Version() uint32 {
	return script.version
}
func (script *RegistrationScript) Type() CTAUTScriptType {
	return script.scriptType
}
func (script *RegistrationScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *RegistrationScript) Serialize() ([]byte, error) {
	// todo(ctaut): initialize a space first?
	// w := bytes.NewBuffer(make([]byte,script.SerializeSize()))
	var b bytes.Buffer
	var err error

	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutSymbol); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.baseUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.subUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, script.unitScale); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for AutMemo
	if err = writeAutMemo(&b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for writeIssuerTokens
	if err = writeIssuerTokens(&b, script.issuerTokens); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, uint64(script.expireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for writeMemo
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}
	fmt.Printf("%d\n", b.Len())

	return b.Bytes(), nil
}
func (script *RegistrationScript) Deserialize(r io.Reader) error {
	var err error

	// todo: not necessary for define a function readPrefix,
	// todo: even do this, the expected Type should be used inside the function
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, Registration); err != nil {
		return err
	}

	if script.ctAutName, err = ReadVarBytes(r, MaxCTAUTNameLength, "name"); err != nil {
		return err
	}
	if script.ctAutSymbol, err = ReadVarBytes(r, MaxCTAUTSymbolLength, "symbol"); err != nil {
		return err
	}
	if script.baseUnitName, err = ReadVarBytes(r, MaxBaseUnitLength, "baseUnit"); err != nil {
		return err
	}
	if script.subUnitName, err = ReadVarBytes(r, MaxSubUnitLength, "subUnit"); err != nil {
		return err
	}
	if script.unitScale, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}
	// todo: not necessary define this function, since this function hides the details, but it is not a structure
	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}
	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	script.expireHeight = int32(expireHeight)

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: not necessary to define this function.
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	return script.SanityCheck()
}

func (script *RegistrationScript) SanityCheck() error {
	// todo(ctaut): check version
	if script.scriptType != Registration {
		return errors.New("unexpected type for registration script")
	}

	if !bytes.Equal(script.ctAutIdentifier[:], zeroIdentifier[:]) {
		return ErrInValidAUTTx
	}
	if len(script.ctAutName) == 0 || len(script.ctAutName) > MaxCTAUTNameLength {
		return ErrInValidAUTTx
	}
	if len(script.ctAutSymbol) == 0 || len(script.ctAutSymbol) > MaxCTAUTSymbolLength {
		return ErrInValidAUTTx
	}

	if len(script.baseUnitName) == 0 || len(script.baseUnitName) > MaxBaseUnitLength {
		return ErrInValidAUTTx
	}
	if len(script.subUnitName) == 0 || len(script.subUnitName) > MaxSubUnitLength {
		return ErrInValidAUTTx
	}
	if script.unitScale == 0 || script.unitScale > MaxAmount || script.unitScale > script.plannedTotalAmount {
		return ErrInValidAUTTx
	}
	if len(script.ctAutMemo) > MaxCTAUTMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > MaxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > MaxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.expireHeight <= 0 || script.expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}
func (script *RegistrationScript) NumConsumedTokens() int {
	return 0
}
func (script *RegistrationScript) NumGeneratedTokens() int {
	return int(script.outAutRootTokenNum)
}

func (script *RegistrationScript) ExpireHeight() int32 {
	return script.expireHeight
}

var _ CTAUTScript = &RegistrationScript{}

// ReRegistrationScript would be the structured script parsed from memo in host transaction,
// 1. The field values used to update the metadata will be extracted from the scripts with ReRegistrationScript.UpdateMetadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// ReRegistrationScript would be serialized with following format
// Flag = "CTAUTReRegistration"
// <Common Prefix> "CTAUTSCRIPT" "1"
// <Identifier> a byte array with fixed length, would not be changed anymore
// <AUTMemo> a byte array with max length
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of consumed RootTokens> A number m, explicitly specify the 0~(m-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of generated RootTokens> A number n, Explicitly specify the 0~(n-1)-th pseudonym TXO of outputs in host transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type ReRegistrationScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	ctAutMemo []byte

	plannedTotalAmount  uint64
	issuerTokens        [][]byte
	mintThreshold       uint8
	reregisterThreshold uint8
	expireHeight        int32

	inAutRootTokenNum  uint8
	outAutRootTokenNum uint8
	memo               []byte // todo: scriptMemo
}

func (script *ReRegistrationScript) CtAutMemo() []byte {
	return script.ctAutMemo
}

func (script *ReRegistrationScript) PlannedTotalAmount() uint64 {
	return script.plannedTotalAmount
}

func (script *ReRegistrationScript) IssuerTokens() [][]byte {
	return script.issuerTokens
}

func (script *ReRegistrationScript) MintThreshold() uint8 {
	return script.mintThreshold
}

func (script *ReRegistrationScript) ReregisterThreshold() uint8 {
	return script.reregisterThreshold
}

func NewReRegistrationScript(
	version uint32,
	ctAutIdentifier [CTAUTIdentifierLength]byte,
	ctAutMemo []byte,
	plannedTotalAmount uint64,
	issuerTokens [][]byte,
	mintThreshold uint8,
	reregisterThreshold uint8,
	expireHeight int32,
	inAutRootTokenNum uint8,
	outAutRootTokenNum uint8,
	memo []byte,
) *ReRegistrationScript {
	return &ReRegistrationScript{
		version:             version,
		scriptType:          ReRegistration,
		ctAutIdentifier:     ctAutIdentifier,
		ctAutMemo:           ctAutMemo,
		plannedTotalAmount:  plannedTotalAmount,
		issuerTokens:        issuerTokens,
		mintThreshold:       mintThreshold,
		reregisterThreshold: reregisterThreshold,
		expireHeight:        expireHeight,
		inAutRootTokenNum:   inAutRootTokenNum,
		outAutRootTokenNum:  outAutRootTokenNum,
		memo:                memo,
	}
}

func (script *ReRegistrationScript) PlannedTotalSupply() uint64 {
	return script.plannedTotalAmount
}

func (script *ReRegistrationScript) ExpireHeight() int32 {
	return script.expireHeight
}

func (script *ReRegistrationScript) Version() uint32 {
	return script.version
}
func (script *ReRegistrationScript) Type() CTAUTScriptType {
	return ReRegistration
}

func (script *ReRegistrationScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *ReRegistrationScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = writeAutMemo(&b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}

	// todo: unnecessary use a function
	if err = writeIssuerTokens(&b, script.issuerTokens); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, uint64(script.expireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *ReRegistrationScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, ReRegistration); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}

	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	if expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}
	script.expireHeight = int32(expireHeight)

	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	return script.SanityCheck()
}

func (script *ReRegistrationScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != ReRegistration {
		return errors.New("unexpected type for re-registration script")
	}

	if len(script.ctAutMemo) > MaxCTAUTMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > MaxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > MaxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.expireHeight <= 0 || script.expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.inAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *ReRegistrationScript) NumConsumedTokens() int {
	return int(script.inAutRootTokenNum)
}
func (script *ReRegistrationScript) NumGeneratedTokens() int {
	return int(script.outAutRootTokenNum)
}

var _ CTAUTScript = &ReRegistrationScript{}

// MintScript would be the structured script parsed from memo in host transaction,
// 1. the minted amount with such a script MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// MintScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "2"
// <Identifier> a byte array with fixed length
// <Vin> an integer, representing the amount of token to be minted, must less than plannedTotalAmount
// <Number of RootToken> A number n, explicitly specify the 0~(n-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type MintScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	vin uint64
	// TODO specify the start index?
	// When generate the script, it must fill the index before creating the transaction
	//	because doesn't know the user how to provide a transaction fee, which is not a reasonable assumption
	// When parse/check the script, it must check the index with a valid host transaction output
	//inStartIndex  uint8 // coin address v.s. issuer token
	inAutRootTokenNum uint8
	//outStartIndex uint8
	outCTAutTokenNum    uint8          // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	outPlainAutTokenNum uint8          // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	valueScripts        [][]byte       // todo: limited to value? // todo: defined as serializedAutTxos? why not autTxos
	witnessHash         chainhash.Hash // todo(ctaut): move to the last position
	memo                []byte         // todo: scriptMemo
}

func (script *MintScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *MintScript) Vin() uint64 {
	return script.vin
}

func NewMintScript(version uint32,
	ctAutIdentifier [CTAUTIdentifierLength]byte,
	vin uint64, inAutRootTokenNum uint8,
	outCTAutTokenNum uint8, outPlainAutTokenNum uint8, valueScripts [][]byte,
	witnessHash chainhash.Hash, memo []byte) *MintScript {
	return &MintScript{
		version:             version,
		scriptType:          Mint,
		ctAutIdentifier:     ctAutIdentifier,
		vin:                 vin,
		inAutRootTokenNum:   inAutRootTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        valueScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *MintScript) Version() uint32 {
	return script.version
}
func (script *MintScript) Type() CTAUTScriptType {
	return script.scriptType
}
func (script *MintScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *MintScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.vin); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil

}
func (script *MintScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, Mint); err != nil {
		return err
	}

	if script.vin, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	// todo: with this check, previous check could be optimied.
	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}

func (script *MintScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != Mint {
		return errors.New("unexpected type for mint script")
	}

	if script.vin == 0 || script.vin > MaxAmount {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) > MaxNumToken {
		return ErrInValidAUTTx
	}

	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}
	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}

		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *MintScript) NumConsumedTokens() int {
	return int(script.inAutRootTokenNum)
}
func (script *MintScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ CTAUTScript = &MintScript{}

// TransferScript would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// TransferScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "3"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type TransferScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	inCTAutTokenNum    uint8
	inPlainAutTokenNum uint8

	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	valueScripts        [][]byte // todo: defined as serializedAutTxos? why not autTxos

	witnessHash chainhash.Hash
	memo        []byte // todo: scriptMemo
}

func (script *TransferScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *TransferScript) Version() uint32 {
	return script.version
}

func NewTransferScript(
	version uint32,
	ctAutIdentifier [CTAUTIdentifierLength]byte,
	inCTAutTokenNum uint8,
	inPlainAutTokenNum uint8,
	outCTAutTokenNum uint8,
	outPlainAutTokenNum uint8,
	autTxoScripts [][]byte,
	witnessHash chainhash.Hash,
	memo []byte,
) *TransferScript {
	return &TransferScript{
		version:             version,
		scriptType:          Transfer,
		ctAutIdentifier:     ctAutIdentifier,
		inCTAutTokenNum:     inCTAutTokenNum,
		inPlainAutTokenNum:  inPlainAutTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        autTxoScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *TransferScript) Type() CTAUTScriptType {
	return script.scriptType
}

func (script *TransferScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *TransferScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *TransferScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, Transfer); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	// todo: sanity check here, so that the above checks could be optimized.
	if err = script.SanityCheck(); err != nil {
		return err
	}
	return nil
}

func (script *TransferScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != Transfer {
		return errors.New("unexpected type for transfer script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}

		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *TransferScript) NumConsumedTokens() int {
	return int(script.inCTAutTokenNum + script.inPlainAutTokenNum)
}
func (script *TransferScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ CTAUTScript = &TransferScript{}

// BurnScript would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts,
// and NOTE THAT the first Plain-Token would be marked burned -> TODO add check logic
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// BurnScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "4"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type BurnScript struct {
	version         uint32
	scriptType      CTAUTScriptType
	ctAutIdentifier [CTAUTIdentifierLength]byte

	inCTAutTokenNum     uint8
	inPlainAutTokenNum  uint8
	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	valueScripts        [][]byte // todo: defined as serializedAutTxos? why not autTxos

	witnessHash chainhash.Hash
	memo        []byte // todo: scriptMemo
}

func (script *BurnScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *BurnScript) Version() uint32 {
	return script.version
}

func NewBurnScript(
	version uint32,
	ctAutIdentifier [CTAUTIdentifierLength]byte,
	inCTAutTokenNum uint8,
	inPlainAutTokenNum uint8,
	outCTAutTokenNum uint8,
	outPlainAutTokenNum uint8,
	valueScripts [][]byte,
	witnessHash chainhash.Hash,
	memo []byte,
) *BurnScript {
	return &BurnScript{
		version:             version,
		scriptType:          Burn,
		ctAutIdentifier:     ctAutIdentifier,
		inCTAutTokenNum:     inCTAutTokenNum,
		inPlainAutTokenNum:  inPlainAutTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        valueScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *BurnScript) Type() CTAUTScriptType {
	return script.scriptType
}

func (script *BurnScript) Identifier() [CTAUTIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *BurnScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

// todo(ctaut): add a standalone sanity-check function, and call it at the end of deserialize
func (script *BurnScript) Deserialize(r io.Reader) error {
	var err error
	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, Burn); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	//	todo: sanity check can optimize the above checks
	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}
func (script *BurnScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != Burn {
		return errors.New("unexpected type for burn script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}
		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	// todo: the burned one must be plainAut

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}
func (script *BurnScript) NumConsumedTokens() int {
	return int(script.inCTAutTokenNum + script.inPlainAutTokenNum)
}
func (script *BurnScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ CTAUTScript = &BurnScript{}

var ErrNonAutTx = errors.New("not a AUT transaction")
var ErrInValidAUTTx = errors.New("not a valid AUT transaction")

// ParseCTAUTScript try to deserialize CTAUT script from transaction memo
// todo: rename memo to TxMemo
// todo: why not use a MsgTxAbe as input?
func ParseCTAUTScript(txVersion uint32, txHash chainhash.Hash, memo []byte) (script CTAUTScript, err error) {
	if txVersion < wire.TxVersion_Height_450000_Aconcagua {
		return nil, nil
	}

	// could not be an AUT transaction
	if len(memo) < len(commonPrefix) {
		return nil, nil
	}
	if !bytes.Equal(memo[:len(commonPrefix)], []byte(commonPrefix)) {
		return nil, nil
	}

	if len(memo) == len(commonPrefix) {
		return nil, fmt.Errorf("the memo start with %s, but have no content", commonPrefix)
	}

	// todo(ctaut): why +1? "CTAUTSCRIPT" will result (nil, nil) or (nil, err)
	// todo(ctaut): only if ctaut-script's CommonPrefixLength is the the start position, it will be recognized as ctaut-script.
	// todo(ctaut): what "txMemo" should be shown at the front end?

	tmpReader := bytes.NewReader(memo[len(commonPrefix):])
	version, err := ReadVarInt(tmpReader)
	if err != nil {
		return nil, err
	}
	if version > math.MaxUint32 {
		return nil, ErrInValidAUTTx
	}
	// check the script version with the host version
	// todo: use the ScriptVersion and TxVersion rule.
	if uint32(version) != txVersion {
		return nil, ErrInValidAUTTx
	}

	scriptType, err := ReadByte(tmpReader)
	if err != nil {
		return nil, err
	}

	switch scriptType {
	case Registration:
		script = &RegistrationScript{}
	case Mint:
		script = &MintScript{}
	case ReRegistration:
		script = &ReRegistrationScript{}
	case Transfer:
		script = &TransferScript{}
	case Burn:
		script = &BurnScript{}
	default:
		return nil, ErrInValidAUTTx
	}

	// reset the reader to deserialize the complete script
	reader := bytes.NewBuffer(memo)
	// todo: here use read; separate Write/Read and Serialize/Deserialize
	// todo: using Deserialize is also fine. [:]
	err = script.Deserialize(reader)
	if err != nil {
		return nil, err
	}

	// check the script version with the host version
	if script.Version() != txVersion {
		return nil, ErrInValidAUTTx
	}

	// populate the identifier for registration script
	if script.Type() == Registration {
		ctAUTScript, ok := script.(*RegistrationScript)
		if !ok {
			return nil, ErrInValidAUTTx
		}
		ctAUTScript.ctAutIdentifier = txHash
	}

	return script, nil
}

// todo(ctaut): this is for database storage or only memeory? why has CoinAddress and ValueScript?
// todo(ctaut): define an interface? only a case needs coinAddress.
// CTAUTToken holds the main information of token in memory, it would be used to check all rules
type CTAUTToken struct {
	// inheritance from host transaction output
	Version uint32
	// used to track the host location on blockchain
	HostOutPoint HostOutPoint
	// For root token, value script would be nil,
	// For normal token, value script could be interpreted to either a public value or a hidden value
	// with abecryptox.ExtractAutTxoValue()
	// todo: serializedAutTxo, or AutTxo?
	ValueScript []byte // todo(ctaut): used to denote AUT value.
	// For all token, coin address would be used to indicate the ownership of token
	// For root token, it would be used match the claimed issuers to recognize operational permission
	CoinAddress []byte
}

// todo: what is this?
type EnhancedCTAUTScript struct {
	CTAUTScript

	// Note that for following 2 fields:
	// - if the value is nil, it means that the tokens is not set
	// - if the value is empty slice, it means that the tokens is set but has no token
	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *EnhancedCTAUTScript) ConsumedTokens() ([]*CTAUTToken, error) {
	if script.consumedTokens == nil {
		return nil, errors.New("consumed tokens not set")
	}

	return script.consumedTokens, nil
}
func (script *EnhancedCTAUTScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != script.NumConsumedTokens() {
		return errors.New("mismatched number of consumed tokens")
	}

	script.consumedTokens = consumedTokens
	return nil
}

func (script *EnhancedCTAUTScript) GeneratedTokens() ([]*CTAUTToken, error) {
	if script.generatedTokens == nil {
		return nil, errors.New("generated tokens not set")
	}

	return script.generatedTokens, nil
}
func (script *EnhancedCTAUTScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != script.NumGeneratedTokens() {
		return errors.New("mismatched number of consumed tokens")
	}

	script.generatedTokens = generatedTokens

	return nil
}

// todo: AutMetadata
func (script *EnhancedCTAUTScript) Metadata() (*AutMetadata, error) {
	if script.Type() != Registration {
		return nil, errors.New("metadata only available for registration script")
	}
	if script.generatedTokens == nil {
		return nil, errors.New("generated tokens not set")
	}

	registerScript, ok := script.CTAUTScript.(*RegistrationScript)
	if !ok {
		return nil, errors.New("metadata only available for registration script")
	}

	rootTokenSet := map[HostOutPoint]struct{}{}
	for i := 0; i < len(script.generatedTokens); i++ {
		rootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}
	metadata := &AutMetadata{
		Version:                 registerScript.version,
		CTAutIdentifier:         registerScript.ctAutIdentifier,
		CTAutName:               registerScript.ctAutName,
		CTAutSymbol:             registerScript.ctAutSymbol,
		BaseUnitName:            registerScript.baseUnitName,
		SubUnitName:             registerScript.subUnitName,
		UnitScale:               registerScript.unitScale,
		CTAutMemo:               registerScript.ctAutMemo,
		PlannedTotalSupply:      registerScript.plannedTotalAmount,
		IssuerTokens:            registerScript.issuerTokens,
		MintThreshold:           registerScript.mintThreshold,
		ReregistrationThreshold: registerScript.reregisterThreshold,
		ExpireHeight:            registerScript.expireHeight,

		MintedAmount: 0,
		BurnedAmount: 0,
		RootTokenSet: rootTokenSet,
	}
	return metadata, nil
}

// todo: AutMetadata
func (script *EnhancedCTAUTScript) UpdateMetadata(metadata *AutMetadata) error {
	// assert
	if script.Type() != ReRegistration {
		return errors.New("update metadata only available for re-registration script")
	}
	identifier := script.Identifier()
	if !bytes.Equal(identifier[:], metadata.CTAutIdentifier[:]) {
		return ErrInValidAUTTx
	}
	consumedTokens := script.consumedTokens
	for i := 0; i < len(consumedTokens); i++ {
		if _, ok := metadata.RootTokenSet[consumedTokens[i].HostOutPoint]; !ok {
			return fmt.Errorf("an re-registration AUT transaction try to update AUT "+
				"with non-existing/spent root token (%s,%d) for AUT identified by %s",
				consumedTokens[i].HostOutPoint.TxHash, consumedTokens[i].HostOutPoint.Index,
				metadata.CTAutIdentifier)
		}
		delete(metadata.RootTokenSet, consumedTokens[i].HostOutPoint)
	}

	reRegisterScript, ok := script.CTAUTScript.(*ReRegistrationScript)
	if !ok {
		return errors.New("update metadata only available for re-registration script")
	}
	metadata.CTAutMemo = reRegisterScript.ctAutMemo
	// assert here?
	if metadata.MintedAmount > reRegisterScript.plannedTotalAmount {
		return errors.New("re-registration transaction try to make planned amount less than minted amount")
	}
	metadata.PlannedTotalSupply = reRegisterScript.plannedTotalAmount

	metadata.IssuerTokens = reRegisterScript.issuerTokens
	metadata.MintThreshold = reRegisterScript.mintThreshold
	metadata.ReregistrationThreshold = reRegisterScript.reregisterThreshold
	metadata.ExpireHeight = reRegisterScript.expireHeight

	// remove previous root tokens
	metadata.RootTokenSet = make(map[HostOutPoint]struct{}, len(script.generatedTokens))
	for i := 0; i < len(script.generatedTokens); i++ {
		metadata.RootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}

	return nil
}

// ExtractCTAUTScript try to deserialize CTAUT script from transaction memo
// if success, it would :
// - extract the well-formed script from memo with sanity check:
//   - no conflict configuration
//   - no token parasitized in invalid host output
//
// - populate the generated tokens by CTAUT script by populateGeneratedTokens
//
// Note that the legality of consumed tokens and the effect of script MUST be checked
// with the help of instance on blockchain.
// - legality of host transaction input
//   - no double/duplicate spending token
//
// - legality of witness
// - effect on the instance
//   - no overflow
//
// todo: CTAUT to Aut?
// todo: what is the relation with Parse
func ExtractCTAUTScript(tx *wire.MsgTxAbe) (enhancedScript *EnhancedCTAUTScript, err error) {
	if tx.Version < wire.TxVersion_Height_450000_Aconcagua {
		return nil, nil
	}
	// parse script from memo and check well-formedness
	autScript, err := ParseCTAUTScript(tx.Version, tx.TxHash(), tx.TxMemo)
	if err != nil {
		return nil, err
	}
	if autScript == nil {
		return nil, nil
	}

	// populate the generated tokens with host transaction outputs
	enhancedScript = &EnhancedCTAUTScript{
		CTAUTScript:     autScript,
		consumedTokens:  nil,
		generatedTokens: nil,
	}
	tokens, err := GetGeneratedCTAUTTokens(autScript, tx.TxHash(), tx.TxOuts)
	if err != nil {
		return nil, err
	}
	err = enhancedScript.setGeneratedTokens(tokens)
	if err != nil {
		return nil, err
	}

	switch script := autScript.(type) {
	case *RegistrationScript:
		// for inputs, there is no rules

		// for outputs, the claimed issuer tokens must match the generated tokens exactly
		// - all issuer tokens must appear
		// - no unclaimed issuer token appear
		if err = matchIssuerTokens(script.issuerTokens, tokens); err != nil {
			return nil, err
		}
	case *ReRegistrationScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the re-register threshold is meet
		// Above checks have to be delayed until the instance could be seen

		// for outputs, the claimed issuer tokens must match the outputs exactly
		if err = matchIssuerTokens(script.issuerTokens, tokens); err != nil {
			return nil, err
		}
	case *MintScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the mint threshold is meet
		// 3. check the balance proof
		// 4. check whether minted amount conflict with planned total amount
		// Above checks have to be delayed until the instance could be seen

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}

	case *TransferScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the balance proof
		// Above checks have to be delayed until the instance could be seen

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}

	case *BurnScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the balance proof
		// Above checks have to be delayed until the instance could be seen

		// for outputs, check the legality of burned token (a.k.a last generated token)
		// Above ParseCTAUTScript() ensures the length of valueScripts is not less than 1
		autTxo := &ctautwire.AutTxo{}
		err = autTxo.Deserialize(script.valueScripts[len(script.valueScripts)-1])
		if err != nil {
			return nil, err
		}
		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return nil, fmt.Errorf("fail to get last aut txo type from burn script: %v")
		}
		// assert the last aut txo is public
		if autTxoType != abecryptox.AutTxoTypePublic {
			return nil, fmt.Errorf("last aut txo type must not public")
		}

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}
	default:
		return nil, ErrInValidAUTTx
	}

	return enhancedScript, nil
}

// PresetHostOutpointForCTAUT would preset the host outpoint for consumed tokens with the help of
// host transaction and ring
// todo: use the correcy HostOutPoint
func PresetHostOutpointForCTAUT(script *EnhancedCTAUTScript, msgTx *wire.MsgTxAbe,
	lookupHostOutput func(ringHash chainhash.Hash) (*wire.TxOutAbe, error),
) error {
	if script == nil || script.CTAUTScript == nil {
		return nil
	}
	if script.Type() == Registration {
		return script.setConsumedTokens([]*CTAUTToken{})
	}
	txHash := msgTx.TxHash()

	hostedTxIns := msgTx.TxIns
	startIndex := 0
	for ; startIndex < len(hostedTxIns); startIndex++ {
		ringHash := hostedTxIns[startIndex].PreviousOutPointRing.Hash()
		txOut, err := lookupHostOutput(ringHash)
		if err != nil {
			return err
		}

		privacyLevel, err := abecryptox.GetTxoPrivacyLevel(txOut)
		if err != nil {
			return err
		}

		// skip fully-privacy area
		if privacyLevel == abecryptoxkey.PrivacyLevelRINGCTPre ||
			privacyLevel == abecryptoxkey.PrivacyLevelRINGCT {
			continue
		}

		if privacyLevel != abecryptoxkey.PrivacyLevelPSEUDONYMCT {
			return fmt.Errorf("expect privacy level %d but got %d",
				abecryptoxkey.PrivacyLevelPSEUDONYMCT, privacyLevel)
		}
		break
	}

	numInCoins := script.NumConsumedTokens()
	if startIndex+numInCoins > len(hostedTxIns) {
		return fmt.Errorf("claim %d (root) coins but only remain %d outputs",
			numInCoins, len(hostedTxIns)-startIndex)
	}

	consumedTokens := make([]*CTAUTToken, numInCoins)
	for i := 0; i < len(consumedTokens); i++ {
		hostIndex := startIndex + i

		// sanity-check
		ringHash := hostedTxIns[hostIndex].PreviousOutPointRing.Hash()
		txOut, err := lookupHostOutput(ringHash)
		if err != nil {
			return err
		}

		privacyLevel, err := abecryptox.GetTxoPrivacyLevel(txOut)
		if err != nil {
			return err
		}
		if privacyLevel != abecryptoxkey.PrivacyLevelPSEUDONYMCT {
			return fmt.Errorf("expect privacy level %d but got %d",
				abecryptoxkey.PrivacyLevelPSEUDONYMCT, privacyLevel)
		}

		// fill out with the first item in ring
		ringIdx := 0
		outpoint := HostOutPoint{
			TxHash: hostedTxIns[hostIndex].PreviousOutPointRing.OutPoints[ringIdx].TxHash,
			Index:  hostedTxIns[hostIndex].PreviousOutPointRing.OutPoints[ringIdx].Index,
		}

		coinAddress, err := CheckHostTxoParasiticity(outpoint.TxHash, outpoint.Index, txOut)
		if err != nil {
			return fmt.Errorf("transaction %s try to consume UTXO at Ring %s is not a valid output", txHash,
				hostedTxIns[hostIndex].PreviousOutPointRing.Hash())
		}

		err = abecryptox.AutRuleCheckOnTxInputVersion(hostedTxIns[hostIndex].PreviousOutPointRing.Version, msgTx.Version)
		if err != nil {
			return fmt.Errorf("transaction %s try to consume CT-AUT token %s with version %d, but tx version is %d",
				txHash, outpoint,
				hostedTxIns[hostIndex].PreviousOutPointRing.Version, msgTx.Version)
		}

		consumedTokens[i] = &CTAUTToken{
			HostOutPoint: outpoint,
			Version:      hostedTxIns[hostIndex].PreviousOutPointRing.Version,
			ValueScript:  nil,         // will be populated later with CTAUTViewpoint
			CoinAddress:  coinAddress, // required by root coin while optional for coin
		}
	}
	return script.setConsumedTokens(consumedTokens)
}
