package ctaut

import (
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"reflect"

	"github.com/abesuite/abec/abecryptox"
	"github.com/abesuite/abec/abecryptox/abecryptoxkey"
	"github.com/abesuite/abec/chainhash"
	ctautwire "github.com/abesuite/abec/ctaut/wire"
	"github.com/abesuite/abec/wire"
)

// HostOutPoint defines the host of aut token, it could be used to track previous tokens.
type HostOutPoint = wire.OutPointAbe

// AutMetadata maintains the metadata information of Abelian User Token (AUT) instance on Abelian
// 1. The identifier of AUT instance are UNIQUE
// 2. Each instance has its own name, symbol, and unit name
// 3. Each instance has its planned total issued amount
// 4. Each instance has issuers, each minting and updating is required to meet the preset threshold
// 5. Issuers are responsible for maintaining the metadata before the expired height.
//
// In details:
// RegistrationScript would register a new instance with unique CTAutIdentifier on Abelian, and generate some special
// tokens, named 'root token', that would be consumed by MintScript or ReRegistrationScript
//
// MintScript would be used to issue normal tokens (a.k.a token), and it would consume some root tokens in ActiveRootTokenSet,
// and also update the MintedAmount
//
// ReRegistrationScript would be used to update the metadata information, including fields PlannedTotalSupply /
// IssuerTokens / MintThreshold / ReregistrationThreshold / ReregistrationExpireHeight
//
// # TransferScript would be used to transfer tokens between users, it would not affect any of the fields in Metadata
//
// BurnScript would be used to burn some tokens, it would not affect any of the fields in Metadata
// todo: discuss use AutXXX, rather than CTAut ? affect too much?
// todo: rename to AutMetadata?
type AutMetadata struct {
	Version uint32
	// The TxHash of the host transaction (i.e. txid) where the registration script is located would be used as its instance identifier
	// identifiers for different instances are unique
	AutIdentifier chainhash.Hash // use chainhash.Hash directly
	// The name of token could be used to improve usability, but MUST NOT be assumed that the value must be present
	// The full, descriptive and human-readable name of the token
	// e.g. "Post-Quantum USD"
	AutName []byte
	// The symbol of token could be used to improve usability, but MUST NOT be assumed that the value must be present.
	// A short, human-readable string that acts as a ticker for the token.
	// e.g. "PQUSD"
	AutSymbol []byte
	// The name he commonly used units of tokens, could be used to user representation,
	// but MUST NOT be assumed that the value must be present
	// e.g. "USD"
	BaseUnitName []byte
	// The name of the token used for counting
	// but MUST NOT be assumed that the value must be present
	// e.g. "Cent"
	SubUnitName []byte
	// The scale between BaseUnit and SubUnit
	// e.g. 100
	UnitScale uint64
	// The memo for AUT instance
	AutMemo []byte

	// The total amount of token would be issued, this means total limit for all MintScript
	// Note that the amount would be counted in terms of subunit
	PlannedTotalSupply uint64
	// The issuers of CT-AUT instance, currently, identified by its coin address on Abelian
	IssuerTokens [][]byte

	// The next ReRegistrationScript must be recorded before this height, otherwise the instance would not update anymore
	// todo: consider never expiring with -1(confirmed: use const)?
	ReregistrationExpireHeight int32 // ReregistrationExpireHeight

	// The number of different issuers in a ReRegistrationScript must meet this threshold to make it valid
	ReregistrationThreshold uint8

	// The number of different issuers in a MintScript must meet this threshold to make it valid
	MintThreshold uint8

	// The minted amount of token
	MintedAmount uint64
	// The burned amount of token
	BurnedAmount uint64 // TODO add this field and logic
	// The following fields hold the currently available root tokens, held by Issuers
	// generated by RegistrationScript or ReRegistrationScript and consumed by MintScript
	// Each RootToken is an unspent host-OutPoint.
	// todo: discuss, use a key-value format? to be more more safe.
	ActiveRootTokenSet map[HostOutPoint]struct{}
}

func (autMetadata *AutMetadata) serializeSize() int {
	n := wire.VarIntSerializeSize(uint64(autMetadata.Version)) + //version
		wire.VarIntSerializeSize(uint64(len(autMetadata.AutIdentifier))) + len(autMetadata.AutIdentifier) + // identifier, actually fixed length
		wire.VarIntSerializeSize(uint64(len(autMetadata.AutName))) + len(autMetadata.AutName) + // name, variable length
		wire.VarIntSerializeSize(uint64(len(autMetadata.AutSymbol))) + len(autMetadata.AutSymbol) + // symbol, variable length
		wire.VarIntSerializeSize(uint64(len(autMetadata.BaseUnitName))) + len(autMetadata.BaseUnitName) + // base unit, variable length
		wire.VarIntSerializeSize(uint64(len(autMetadata.SubUnitName))) + len(autMetadata.SubUnitName) + // sub unit, variable length
		wire.VarIntSerializeSize(autMetadata.UnitScale) + // scale, variable length
		wire.VarIntSerializeSize(uint64(len(autMetadata.AutMemo))) + len(autMetadata.AutMemo) // memo, variable length

	n += wire.VarIntSerializeSize(autMetadata.PlannedTotalSupply) // planned amount

	n += wire.VarIntSerializeSize(uint64(len(autMetadata.IssuerTokens))) // number of issuer tokens
	for i := 0; i < len(autMetadata.IssuerTokens); i++ {
		// actually fixed length
		n += wire.VarIntSerializeSize(uint64(len(autMetadata.IssuerTokens[i]))) + len(autMetadata.IssuerTokens[i])
	}

	n += wire.VarIntSerializeSize(uint64(autMetadata.ReregistrationExpireHeight)) // ReregistrationExpireHeight

	n += 1 + // reregister threshold
		1 // mint threshold

	n += wire.VarIntSerializeSize(autMetadata.MintedAmount) + // minted amount,variable length
		wire.VarIntSerializeSize(autMetadata.BurnedAmount) // burned amount,variable length

	n += wire.VarIntSerializeSize(uint64(len(autMetadata.ActiveRootTokenSet))) // number of issuer tokens
	for hostOutPoint := range autMetadata.ActiveRootTokenSet {
		n += hostOutPoint.SerializeSize()
	}

	return n
}

// Serialize serializes AutMetadata to []byte.
// call abec.wire.WriteVarInt or call locally WriteVarInt?
func (autMetadata *AutMetadata) Serialize() ([]byte, error) {
	if autMetadata == nil {
		return nil, nil
	}
	// Calculate the size needed to serialize AUT autMetadata.
	var err error
	size := autMetadata.serializeSize()
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	w := bytes.NewBuffer(make([]byte, 0, size))

	if err = wire.WriteVarInt(w, 0, uint64(autMetadata.Version)); err != nil {
		return nil, err
	}

	// to be extensible, here use VarBytes rather than fixed-length bytes.
	// todo: discuss, how about use fixed bytes. It is unnecessary to leave space extension here.
	if err = wire.WriteVarBytes(w, 0, autMetadata.AutIdentifier[:]); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(w, 0, autMetadata.AutName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(w, 0, autMetadata.AutSymbol); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(w, 0, autMetadata.BaseUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarBytes(w, 0, autMetadata.SubUnitName); err != nil {
		return nil, err
	}
	if err = wire.WriteVarInt(w, 0, autMetadata.UnitScale); err != nil {
		return nil, err
	}

	if err = wire.WriteVarBytes(w, 0, autMetadata.AutMemo); err != nil {
		return nil, err
	}

	if err = wire.WriteVarInt(w, 0, autMetadata.PlannedTotalSupply); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(w, 0, uint64(len(autMetadata.IssuerTokens)))
	if err != nil {
		return nil, err
	}
	for i := 0; i < len(autMetadata.IssuerTokens); i++ {
		err = wire.WriteVarBytes(w, 0, autMetadata.IssuerTokens[i])
		if err != nil {
			return nil, fmt.Errorf("error to write issuer token: %v", err)
		}
	}

	if err = wire.WriteVarInt(w, 0, uint64(autMetadata.ReregistrationExpireHeight)); err != nil {
		return nil, err
	}

	if err = w.WriteByte(autMetadata.ReregistrationThreshold); err != nil {
		return nil, err
	}
	if err = w.WriteByte(autMetadata.MintThreshold); err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(w, 0, autMetadata.MintedAmount)
	if err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(w, 0, autMetadata.BurnedAmount)
	if err != nil {
		return nil, err
	}

	err = wire.WriteVarInt(w, 0, uint64(len(autMetadata.ActiveRootTokenSet)))
	if err != nil {
		return nil, err
	}
	for hostOutPoint := range autMetadata.ActiveRootTokenSet {
		err = wire.WriteOutPointAbe(w, 0, 0, &hostOutPoint)
		if err != nil {
			return nil, fmt.Errorf("error to write active root token: %v", err)
		}
	}

	serializedMetadata := w.Bytes()

	// todo: the following codes are necessary or only for test?
	tmpMetadata := &AutMetadata{}
	err = tmpMetadata.Deserialize(serializedMetadata)
	if err != nil {
		return nil, err
	}
	if !reflect.DeepEqual(autMetadata, tmpMetadata) {
		return nil, errors.New("metadata not match after serialization")
	}

	return serializedMetadata, nil
}

// Deserialize deserializes serializedMetadata to an AutMetadata.
func (autMetadata *AutMetadata) Deserialize(serializedMetadata []byte) error {
	// Serialize the header code followed by the compressed unspent
	// transaction output.
	r := bytes.NewReader(serializedMetadata)

	var err error
	version, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	if version > math.MaxUint32 {
		return fmt.Errorf("readed version (%d) is too large", version)
	}
	autMetadata.Version = uint32(version)

	identifier, err := wire.ReadVarBytes(r, 0, AutIdentifierLength, "identifier")
	if err != nil {
		return err
	}
	// This check-fail could not be detected in sanity-check, has to be conducted here.
	if len(identifier) != AutIdentifierLength {
		return errors.New("unexpected identifier length")
	}
	copy(autMetadata.AutIdentifier[:], identifier)

	if autMetadata.AutName, err = wire.ReadVarBytes(r, 0, MaxAutNameLength, "name"); err != nil {
		return err
	}
	if autMetadata.AutSymbol, err = wire.ReadVarBytes(r, 0, MaxAutSymbolLength, "symbol"); err != nil {
		return err
	}
	if autMetadata.BaseUnitName, err = wire.ReadVarBytes(r, 0, MaxBaseUnitLength, "unit"); err != nil {
		return err
	}
	if autMetadata.SubUnitName, err = wire.ReadVarBytes(r, 0, MaxSubUnitLength, "subunit"); err != nil {
		return err
	}
	if autMetadata.UnitScale, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}
	if autMetadata.AutMemo, err = wire.ReadVarBytes(r, 0, MaxAutMemoLength, "AutMemo"); err != nil {
		return err
	}

	if autMetadata.PlannedTotalSupply, err = wire.ReadVarInt(r, 0); err != nil {
		return err
	}

	issuerNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	autMetadata.IssuerTokens = make([][]byte, issuerNum)
	for i := uint64(0); i < issuerNum; i++ {
		autMetadata.IssuerTokens[i], err = wire.ReadVarBytes(r, 0, issuerTokenLength, "issuerToken")
		if err != nil {
			return fmt.Errorf("error when reading issuer token: %v", err)
		}
	}

	expiredHeightRead, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	temp := int64(expiredHeightRead)
	if temp > math.MaxInt32 || temp < -1 {
		return fmt.Errorf("the read ReregistrationExpireHeight (%d) is not in the scope [-1, %d]", temp, math.MaxInt32)
	}
	autMetadata.ReregistrationExpireHeight = int32(temp)

	if autMetadata.ReregistrationThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if autMetadata.MintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	autMetadata.MintedAmount, err = wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	autMetadata.BurnedAmount, err = wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}

	rootCoinNum, err := wire.ReadVarInt(r, 0)
	if err != nil {
		return err
	}
	autMetadata.ActiveRootTokenSet = make(map[HostOutPoint]struct{}, rootCoinNum)
	for i := uint64(0); i < rootCoinNum; i++ {
		hostOutPoint := HostOutPoint{}
		err = wire.ReadOutPointAbe(r, 0, 0, &hostOutPoint)
		if err != nil {
			return fmt.Errorf("error when reading active root token: %v", err)
		}
		autMetadata.ActiveRootTokenSet[hostOutPoint] = struct{}{}
	}
	if uint64(len(autMetadata.ActiveRootTokenSet)) != rootCoinNum {
		return fmt.Errorf("the number of read active root token (%d) does not match the read number (%d)",
			len(autMetadata.ActiveRootTokenSet), rootCoinNum)
	}

	return autMetadata.SanityCheck()
}

// SanityCheck checks whether the AutMetadata is well-formed, and return a non-nil error if it is not well-formed.
func (autMetadata *AutMetadata) SanityCheck() error {
	// todo: add version check
	// todo: add identifier check
	if len(autMetadata.AutName) > MaxAutNameLength {
		return fmt.Errorf("invalid length (%d) for aut name", len(autMetadata.AutName))
	}
	if len(autMetadata.AutSymbol) > MaxAutSymbolLength {
		return fmt.Errorf("invalid length (%d) for aut symbol", len(autMetadata.AutSymbol))
	}
	if len(autMetadata.BaseUnitName) > MaxBaseUnitLength {
		return fmt.Errorf("invalid length (%d) for base unit name", len(autMetadata.BaseUnitName))
	}
	if len(autMetadata.SubUnitName) > MaxSubUnitLength {
		return fmt.Errorf("invalid length (%d) for sub unit name", len(autMetadata.SubUnitName))
	}
	if len(autMetadata.AutMemo) > MaxAutMemoLength {
		return fmt.Errorf("invalid length (%d) for aut memo", len(autMetadata.AutMemo))
	}
	if autMetadata.PlannedTotalSupply > MaxAmount {
		return fmt.Errorf("invalid planned total supply (%d)", autMetadata.PlannedTotalSupply)
	}

	issuerTokenMapping := map[string]struct{}{}
	for _, issuerToken := range autMetadata.IssuerTokens {
		key := hex.EncodeToString(issuerToken)
		if _, ok := issuerTokenMapping[key]; ok {
			return fmt.Errorf("repeated issuer tokens exist")
		}
		issuerTokenMapping[key] = struct{}{}
	}

	if autMetadata.ReregistrationExpireHeight < InfiniteExpireHeight {
		return fmt.Errorf("invalid reregistration expire height (%d)", autMetadata.ReregistrationExpireHeight)
	}

	if autMetadata.ReregistrationThreshold > uint8(len(autMetadata.IssuerTokens)) {
		return fmt.Errorf("invalid reregistration threshold (%d) for %d issuer tokens", autMetadata.ReregistrationThreshold, len(autMetadata.IssuerTokens))
	}
	if autMetadata.MintThreshold > uint8(len(autMetadata.IssuerTokens)) {
		return fmt.Errorf("invalid mint threshold (%d) for %d issuer tokens", autMetadata.MintThreshold, len(autMetadata.IssuerTokens))
	}

	if autMetadata.MintedAmount > autMetadata.PlannedTotalSupply {
		return fmt.Errorf("invalid minted amount (%d) for planned total supply (%d)", autMetadata.MintedAmount, autMetadata.PlannedTotalSupply)
	}
	if autMetadata.BurnedAmount > autMetadata.MintedAmount {
		return fmt.Errorf("invalid burned amount (%d) for minted amount (%d)", autMetadata.BurnedAmount, autMetadata.MintedAmount)
	}

	return nil
}

// Clone returns a shallow copy of the utxo entry.
func (autMetadata *AutMetadata) Clone() *AutMetadata {
	if autMetadata == nil {
		return nil
	}

	cloned := &AutMetadata{
		Version:       autMetadata.Version,
		AutIdentifier: chainhash.Hash{},

		AutName:            make([]byte, len(autMetadata.AutName)),
		AutSymbol:          make([]byte, len(autMetadata.AutSymbol)),
		BaseUnitName:       make([]byte, len(autMetadata.BaseUnitName)),
		SubUnitName:        make([]byte, len(autMetadata.SubUnitName)),
		UnitScale:          autMetadata.UnitScale,
		AutMemo:            make([]byte, len(autMetadata.AutMemo)),
		PlannedTotalSupply: autMetadata.PlannedTotalSupply,

		IssuerTokens: make([][]byte, len(autMetadata.IssuerTokens)),

		ReregistrationExpireHeight: autMetadata.ReregistrationExpireHeight,
		ReregistrationThreshold:    autMetadata.ReregistrationThreshold,
		MintThreshold:              autMetadata.MintThreshold,

		MintedAmount:       autMetadata.MintedAmount,
		BurnedAmount:       autMetadata.BurnedAmount,
		ActiveRootTokenSet: make(map[HostOutPoint]struct{}, len(autMetadata.ActiveRootTokenSet)),
	}

	copy(cloned.AutIdentifier[:], autMetadata.AutIdentifier[:])

	copy(cloned.AutSymbol, autMetadata.AutSymbol)
	copy(cloned.AutName, autMetadata.AutName)
	copy(cloned.BaseUnitName, autMetadata.BaseUnitName)
	copy(cloned.SubUnitName, autMetadata.SubUnitName)
	copy(cloned.AutMemo, autMetadata.AutMemo)

	for i := 0; i < len(autMetadata.IssuerTokens); i++ {
		cloned.IssuerTokens[i] = make([]byte, len(autMetadata.IssuerTokens[i]))
		copy(cloned.IssuerTokens[i][:], autMetadata.IssuerTokens[i][:])
	}

	for hostOutpoint := range autMetadata.ActiveRootTokenSet {
		newHosOutpoint := HostOutPoint{}
		copy(newHosOutpoint.TxHash[:], hostOutpoint.TxHash[:])
		newHosOutpoint.Index = hostOutpoint.Index

		cloned.ActiveRootTokenSet[newHosOutpoint] = struct{}{}
	}

	return cloned
}

type AutScript interface {
	Version() uint32
	Type() AutScriptType
	Identifier() [AutIdentifierLength]byte

	Serialize() ([]byte, error)
	Deserialize(io.Reader) error // todo: make it to be symmetric? say, take []byte as input?

	NumConsumedTokens() int // todo: why not directly uint8? if leave it to be int, need to check when set this value.
	NumGeneratedTokens() int
}

// RegistrationScript would be the structured script parsed from memo in host transaction,
// 1. the metadata for the instance will be extracted from the script with RegistrationScript.Metadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// RegistrationScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "0"
// <Identifier> a byte array with fixed length TODO remove from script or reserved with zero-bytes?
// <AUTName> a byte array with max length, would not be changed anymore
// <AUSymbol> a byte array with max length, would not be changed anymore
// <baseUnitName> a byte array with max length, would not be changed anymore
// <subUnitName> a byte array with max length, would not be changed anymore
// <UnitScale> the scale between unit and minUnit, would not be changed anymore
// <ctAutMemo> a byte array with max length
//
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of generated RootTokens> A number n, explicitly mark the 0~(n-1)-th pseudonym TXO of this transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type RegistrationScript struct {
	// inheritance from transactions
	// todo: this version is ScriptVersion or the host-transaction's version?
	// todo: or named as ScriptVersion but inherit from and the same as host-transaction's version?
	// todo: consider has its own version field, but has a mapping to host-transaction's Version? this will give extension to the case
	// that the same tx's version may support different autScriptVersion.
	// // todo: if use the above design, the AutTxo.Version should use ScriptVersion, not the host-tx's version.
	version    uint32 // TODO(CTAUT) add version field in script self, check the usage version and the relation with the version in host transaction
	scriptType AutScriptType

	// populate with txid of host transaction
	ctAutIdentifier [AutIdentifierLength]byte

	ctAutName    []byte
	ctAutSymbol  []byte
	baseUnitName []byte
	subUnitName  []byte
	unitScale    uint64
	ctAutMemo    []byte

	plannedTotalAmount         uint64
	issuerTokens               [][]byte
	mintThreshold              uint8
	reregisterThreshold        uint8
	reregistrationExpireHeight int32

	outAutRootTokenNum uint8  // value is set in deserialize, so, do not provide set function, but provide get function.
	memo               []byte // todo: TODO memo -> scriptMemo
}

func (script *RegistrationScript) CtAutName() []byte {
	return script.ctAutName
}

func (script *RegistrationScript) CtAutSymbol() []byte {
	return script.ctAutSymbol
}

func (script *RegistrationScript) BaseUnitName() []byte {
	return script.baseUnitName
}

func (script *RegistrationScript) SubUnitName() []byte {
	return script.subUnitName
}

func (script *RegistrationScript) UnitScale() uint64 {
	return script.unitScale
}

func (script *RegistrationScript) CtAutMemo() []byte {
	return script.ctAutMemo
}

func (script *RegistrationScript) PlannedTotalAmount() uint64 {
	return script.plannedTotalAmount
}

func (script *RegistrationScript) IssuerTokens() [][]byte {
	return script.issuerTokens
}

func (script *RegistrationScript) MintThreshold() uint8 {
	return script.mintThreshold
}

func (script *RegistrationScript) ReregisterThreshold() uint8 {
	return script.reregisterThreshold
}

func (script *RegistrationScript) Memo() []byte {
	return script.memo
}

func NewRegistrationScript(
	version uint32,
	ctAutName []byte,
	ctAutSymbol []byte,
	baseUnitName []byte,
	subUnitName []byte,
	unitScale uint64,
	ctAutMemo []byte,
	plannedTotalAmount uint64,
	issuerTokens [][]byte,
	mintThreshold uint8,
	reregisterThreshold uint8,
	reregistrationExpireHeight int32,
	outAutRootTokenNum uint8,
	memo []byte,
) *RegistrationScript {
	return &RegistrationScript{
		version:                    version,
		scriptType:                 AutScriptTypeRegistration,
		ctAutIdentifier:            [AutIdentifierLength]byte{},
		ctAutName:                  ctAutName,
		ctAutSymbol:                ctAutSymbol,
		baseUnitName:               baseUnitName,
		subUnitName:                subUnitName,
		unitScale:                  unitScale,
		ctAutMemo:                  ctAutMemo,
		plannedTotalAmount:         plannedTotalAmount,
		issuerTokens:               issuerTokens,
		mintThreshold:              mintThreshold,
		reregisterThreshold:        reregisterThreshold,
		reregistrationExpireHeight: reregistrationExpireHeight,
		outAutRootTokenNum:         outAutRootTokenNum,
		memo:                       memo,
	}
}
func (script *RegistrationScript) Version() uint32 {
	return script.version
}
func (script *RegistrationScript) Type() AutScriptType {
	return script.scriptType
}
func (script *RegistrationScript) Identifier() [AutIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *RegistrationScript) Serialize() ([]byte, error) {
	// todo(ctaut): initialize a space first?
	// w := bytes.NewBuffer(make([]byte,script.SerializeSize()))
	var b bytes.Buffer
	var err error

	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.ctAutSymbol); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.baseUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarBytes(&b, script.subUnitName); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, script.unitScale); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for AutMemo
	if err = writeAutMemo(&b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for writeIssuerTokens
	if err = writeIssuerTokens(&b, script.issuerTokens); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}
	if err = WriteVarInt(&b, uint64(script.reregistrationExpireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}
	// todo: not necessary to define a function for writeMemo
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}
	fmt.Printf("%d\n", b.Len())

	return b.Bytes(), nil
}
func (script *RegistrationScript) Deserialize(r io.Reader) error {
	var err error

	// todo: not necessary for define a function readPrefix,
	// todo: even do this, the expected Type should be used inside the function
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, AutScriptTypeRegistration); err != nil {
		return err
	}

	if script.ctAutName, err = ReadVarBytes(r, MaxAutNameLength, "name"); err != nil {
		return err
	}
	if script.ctAutSymbol, err = ReadVarBytes(r, MaxAutSymbolLength, "symbol"); err != nil {
		return err
	}
	if script.baseUnitName, err = ReadVarBytes(r, MaxBaseUnitLength, "baseUnit"); err != nil {
		return err
	}
	if script.subUnitName, err = ReadVarBytes(r, MaxSubUnitLength, "subUnit"); err != nil {
		return err
	}
	if script.unitScale, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}
	// todo: not necessary define this function, since this function hides the details, but it is not a structure
	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}
	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}
	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	script.reregistrationExpireHeight = int32(expireHeight)

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: not necessary to define this function.
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	return script.SanityCheck()
}

func (script *RegistrationScript) SanityCheck() error {
	// todo(ctaut): check version
	if script.scriptType != AutScriptTypeRegistration {
		return errors.New("unexpected type for registration script")
	}

	if !bytes.Equal(script.ctAutIdentifier[:], zeroIdentifier[:]) {
		return ErrInValidAUTTx
	}
	if len(script.ctAutName) == 0 || len(script.ctAutName) > MaxAutNameLength {
		return ErrInValidAUTTx
	}
	if len(script.ctAutSymbol) == 0 || len(script.ctAutSymbol) > MaxAutSymbolLength {
		return ErrInValidAUTTx
	}

	if len(script.baseUnitName) == 0 || len(script.baseUnitName) > MaxBaseUnitLength {
		return ErrInValidAUTTx
	}
	if len(script.subUnitName) == 0 || len(script.subUnitName) > MaxSubUnitLength {
		return ErrInValidAUTTx
	}
	if script.unitScale == 0 || script.unitScale > MaxAmount || script.unitScale > script.plannedTotalAmount {
		return ErrInValidAUTTx
	}
	if len(script.ctAutMemo) > MaxAutMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > MaxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > MaxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.reregistrationExpireHeight < InfiniteExpireHeight || script.reregistrationExpireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}
func (script *RegistrationScript) NumConsumedTokens() int {
	return 0
}
func (script *RegistrationScript) NumGeneratedTokens() int {
	return int(script.outAutRootTokenNum)
}

func (script *RegistrationScript) ReregistrationExpireHeight() int32 {
	return script.reregistrationExpireHeight
}

var _ AutScript = &RegistrationScript{}

// ReRegistrationScript would be the structured script parsed from memo in host transaction,
// 1. The field values used to update the metadata will be extracted from the scripts with ReRegistrationScript.UpdateMetadata()
// 2. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 3. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// ReRegistrationScript would be serialized with following format
// Flag = "CTAUTReRegistration"
// <Common Prefix> "CTAUTSCRIPT" "1"
// <Identifier> a byte array with fixed length, would not be changed anymore
// <AUTMemo> a byte array with max length
// <Planed Total Amount> an integer range in [1, 1<<51 -1)
// <IssuerTokens> an array with length N of hash, each one represents a public key (represented by a pseudonym coin address)
// <ReregistrationThreshold> An integer update_t <= N
// <MintThreshold> An integer mint_t <= N
// <Expiry of IssuerTokens> a height value
//
// <Number of consumed RootTokens> A number m, explicitly specify the 0~(m-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of generated RootTokens> A number n, Explicitly specify the 0~(n-1)-th pseudonym TXO of outputs in host transaction as RootToken
// <Memo> a byte array with max length, for this transaction
type ReRegistrationScript struct {
	version         uint32
	scriptType      AutScriptType
	ctAutIdentifier [AutIdentifierLength]byte

	ctAutMemo []byte

	plannedTotalAmount         uint64
	issuerTokens               [][]byte
	mintThreshold              uint8
	reregisterThreshold        uint8
	reregistrationExpireHeight int32

	inAutRootTokenNum  uint8
	outAutRootTokenNum uint8
	memo               []byte // todo: scriptMemo
}

func (script *ReRegistrationScript) CtAutMemo() []byte {
	return script.ctAutMemo
}

func (script *ReRegistrationScript) PlannedTotalAmount() uint64 {
	return script.plannedTotalAmount
}

func (script *ReRegistrationScript) IssuerTokens() [][]byte {
	return script.issuerTokens
}

func (script *ReRegistrationScript) MintThreshold() uint8 {
	return script.mintThreshold
}

func (script *ReRegistrationScript) ReregisterThreshold() uint8 {
	return script.reregisterThreshold
}

func NewReRegistrationScript(
	version uint32,
	ctAutIdentifier [AutIdentifierLength]byte,
	ctAutMemo []byte,
	plannedTotalAmount uint64,
	issuerTokens [][]byte,
	mintThreshold uint8,
	reregisterThreshold uint8,
	reregistrationExpireHeight int32,
	inAutRootTokenNum uint8,
	outAutRootTokenNum uint8,
	memo []byte,
) *ReRegistrationScript {
	return &ReRegistrationScript{
		version:                    version,
		scriptType:                 AutScriptTypeReRegistration,
		ctAutIdentifier:            ctAutIdentifier,
		ctAutMemo:                  ctAutMemo,
		plannedTotalAmount:         plannedTotalAmount,
		issuerTokens:               issuerTokens,
		mintThreshold:              mintThreshold,
		reregisterThreshold:        reregisterThreshold,
		reregistrationExpireHeight: reregistrationExpireHeight,
		inAutRootTokenNum:          inAutRootTokenNum,
		outAutRootTokenNum:         outAutRootTokenNum,
		memo:                       memo,
	}
}

func (script *ReRegistrationScript) PlannedTotalSupply() uint64 {
	return script.plannedTotalAmount
}

func (script *ReRegistrationScript) ReregistrationExpireHeight() int32 {
	return script.reregistrationExpireHeight
}

func (script *ReRegistrationScript) Version() uint32 {
	return script.version
}
func (script *ReRegistrationScript) Type() AutScriptType {
	return AutScriptTypeReRegistration
}

func (script *ReRegistrationScript) Identifier() [AutIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *ReRegistrationScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = writeAutMemo(&b, script.ctAutMemo); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.plannedTotalAmount); err != nil {
		return nil, err
	}

	// todo: unnecessary use a function
	if err = writeIssuerTokens(&b, script.issuerTokens); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.mintThreshold); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.reregisterThreshold); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, uint64(script.reregistrationExpireHeight)); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outAutRootTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *ReRegistrationScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, AutScriptTypeReRegistration); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.ctAutMemo, err = readAutMemo(r); err != nil {
		return err
	}

	if script.plannedTotalAmount, err = ReadVarInt(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.issuerTokens, err = readIssuerTokens(r); err != nil {
		return err
	}

	if script.mintThreshold, err = ReadByte(r); err != nil {
		return err
	}

	if script.reregisterThreshold, err = ReadByte(r); err != nil {
		return err
	}

	var expireHeight uint64
	if expireHeight, err = ReadVarInt(r); err != nil {
		return err
	}
	tmp := int64(expireHeight)
	if tmp < -1 {
		return ErrInValidAUTTx
	}
	if expireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}
	script.reregistrationExpireHeight = int32(expireHeight)

	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	return script.SanityCheck()
}

func (script *ReRegistrationScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != AutScriptTypeReRegistration {
		return errors.New("unexpected type for re-registration script")
	}

	if len(script.ctAutMemo) > MaxAutMemoLength {
		return ErrInValidAUTTx
	}

	if script.plannedTotalAmount == 0 || script.plannedTotalAmount > MaxAmount {
		return ErrInValidAUTTx
	}
	if len(script.issuerTokens) == 0 || len(script.issuerTokens) > MaxIssuerNum {
		return ErrInValidAUTTx
	}
	if int(script.mintThreshold) == 0 || int(script.mintThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if int(script.reregisterThreshold) == 0 || int(script.reregisterThreshold) > len(script.issuerTokens) {
		return ErrInValidAUTTx
	}
	if script.reregistrationExpireHeight < InfiniteExpireHeight || script.reregistrationExpireHeight > math.MaxInt32 {
		return ErrInValidAUTTx
	}

	if script.inAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outAutRootTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *ReRegistrationScript) NumConsumedTokens() int {
	return int(script.inAutRootTokenNum)
}
func (script *ReRegistrationScript) NumGeneratedTokens() int {
	return int(script.outAutRootTokenNum)
}

var _ AutScript = &ReRegistrationScript{}

// MintScript would be the structured script parsed from memo in host transaction,
// 1. the minted amount with such a script MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// MintScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "2"
// <Identifier> a byte array with fixed length
// <Vin> an integer, representing the amount of token to be minted, must less than plannedTotalAmount
// <Number of RootToken> A number n, explicitly specify the 0~(n-1)-th pseudonym TXO of inputs in host transaction as RootToken
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type MintScript struct {
	version         uint32
	scriptType      AutScriptType
	ctAutIdentifier [AutIdentifierLength]byte

	vin uint64
	// TODO specify the start index?
	// When generate the script, it must fill the index before creating the transaction
	//	because doesn't know the user how to provide a transaction fee, which is not a reasonable assumption
	// When parse/check the script, it must check the index with a valid host transaction output
	//inStartIndex  uint8 // coin address v.s. issuer token
	inAutRootTokenNum uint8
	//outStartIndex uint8
	outCTAutTokenNum    uint8          // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	outPlainAutTokenNum uint8          // todo(ctaut): explicitly specify the number of plain-aut and the number of ct-aut? not specified, will call underlying API to extract AutTxoType?
	valueScripts        [][]byte       // todo: limited to value? // todo: defined as serializedAutTxos? why not autTxos
	witnessHash         chainhash.Hash // todo(ctaut): move to the last position
	memo                []byte         // todo: scriptMemo
}

func (script *MintScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *MintScript) Vin() uint64 {
	return script.vin
}

func NewMintScript(version uint32,
	ctAutIdentifier [AutIdentifierLength]byte,
	vin uint64, inAutRootTokenNum uint8,
	outCTAutTokenNum uint8, outPlainAutTokenNum uint8, valueScripts [][]byte,
	witnessHash chainhash.Hash, memo []byte) *MintScript {
	return &MintScript{
		version:             version,
		scriptType:          AutScriptTypeMint,
		ctAutIdentifier:     ctAutIdentifier,
		vin:                 vin,
		inAutRootTokenNum:   inAutRootTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        valueScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *MintScript) Version() uint32 {
	return script.version
}
func (script *MintScript) Type() AutScriptType {
	return script.scriptType
}
func (script *MintScript) Identifier() [AutIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *MintScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = WriteVarInt(&b, script.vin); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inAutRootTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil

}
func (script *MintScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, AutScriptTypeMint); err != nil {
		return err
	}

	if script.vin, err = ReadVarInt(r); err != nil {
		return err
	}
	if script.inAutRootTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	// todo: with this check, previous check could be optimied.
	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}

func (script *MintScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != AutScriptTypeMint {
		return errors.New("unexpected type for mint script")
	}

	if script.vin == 0 || script.vin > MaxAmount {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) > MaxNumToken {
		return ErrInValidAUTTx
	}

	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}
	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}

		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *MintScript) NumConsumedTokens() int {
	return int(script.inAutRootTokenNum)
}
func (script *MintScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ AutScript = &MintScript{}

// TransferScript would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// TransferScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "3"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type TransferScript struct {
	version         uint32
	scriptType      AutScriptType
	ctAutIdentifier [AutIdentifierLength]byte

	inCTAutTokenNum    uint8
	inPlainAutTokenNum uint8

	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	valueScripts        [][]byte // todo: defined as serializedAutTxos? why not autTxos

	witnessHash chainhash.Hash
	memo        []byte // todo: scriptMemo
}

func (script *TransferScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *TransferScript) Version() uint32 {
	return script.version
}

func NewTransferScript(
	version uint32,
	ctAutIdentifier [AutIdentifierLength]byte,
	inCTAutTokenNum uint8,
	inPlainAutTokenNum uint8,
	outCTAutTokenNum uint8,
	outPlainAutTokenNum uint8,
	autTxoScripts [][]byte,
	witnessHash chainhash.Hash,
	memo []byte,
) *TransferScript {
	return &TransferScript{
		version:             version,
		scriptType:          AutScriptTypeTransfer,
		ctAutIdentifier:     ctAutIdentifier,
		inCTAutTokenNum:     inCTAutTokenNum,
		inPlainAutTokenNum:  inPlainAutTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        autTxoScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *TransferScript) Type() AutScriptType {
	return script.scriptType
}

func (script *TransferScript) Identifier() [AutIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *TransferScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}
func (script *TransferScript) Deserialize(r io.Reader) error {
	var err error

	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, AutScriptTypeTransfer); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	// todo: sanity check here, so that the above checks could be optimized.
	if err = script.SanityCheck(); err != nil {
		return err
	}
	return nil
}

func (script *TransferScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != AutScriptTypeTransfer {
		return errors.New("unexpected type for transfer script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}

		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}

func (script *TransferScript) NumConsumedTokens() int {
	return int(script.inCTAutTokenNum + script.inPlainAutTokenNum)
}
func (script *TransferScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ AutScript = &TransferScript{}

// BurnScript would be the structured script parsed from memo in host transaction,
// 1. the number of consumed CT-Token and Plain-Token MUST be explicit specified
// 2. the number of generated CT-Token and Plain-Token MUST be explicit specified, and corresponding value scripts,
// and NOTE THAT the first Plain-Token would be marked burned -> TODO add check logic
// 3. the witness hash would be computed from AutWitness in host transaction
// 3. consumedTokens would be populated with the help of host transaction and corresponding wire.TxoRing
// 4. generatedTokens would be populated with the function populateGeneratedCTAUTTokens with the help of host transaction
//
// BurnScript would be serialized with following format
// <Common Prefix> "CTAUTSCRIPT" "4"
// <Identifier> a byte array with fixed length
// <Number of CTAUTTokens> A number n, Explicitly specify the 0~(m-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number m, Explicitly specify the n~(n+m-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <Number of CTAUTTokens> A number i, Explicitly specify the 0~(i-1)-th pseudonym TXO of outputs in host transaction as CT-Token
// <Number of PlainTokens> A number j, Explicitly specify the i~(i+j-1)-th pseudonym TXO of outputs in host transaction as Plain-Token
// <ValueScript> an array of n byte array, represent the amount for an AUTToken
// <WitnessHash> a byte array with fixed length
// <Memo> a byte array with max length, for this transaction
type BurnScript struct {
	version         uint32
	scriptType      AutScriptType
	ctAutIdentifier [AutIdentifierLength]byte

	inCTAutTokenNum     uint8
	inPlainAutTokenNum  uint8
	outCTAutTokenNum    uint8
	outPlainAutTokenNum uint8
	valueScripts        [][]byte // todo: defined as serializedAutTxos? why not autTxos

	witnessHash chainhash.Hash
	memo        []byte // todo: scriptMemo
}

func (script *BurnScript) WitnessHash() chainhash.Hash {
	return script.witnessHash
}

func (script *BurnScript) Version() uint32 {
	return script.version
}

func NewBurnScript(
	version uint32,
	ctAutIdentifier [AutIdentifierLength]byte,
	inCTAutTokenNum uint8,
	inPlainAutTokenNum uint8,
	outCTAutTokenNum uint8,
	outPlainAutTokenNum uint8,
	valueScripts [][]byte,
	witnessHash chainhash.Hash,
	memo []byte,
) *BurnScript {
	return &BurnScript{
		version:             version,
		scriptType:          AutScriptTypeBurn,
		ctAutIdentifier:     ctAutIdentifier,
		inCTAutTokenNum:     inCTAutTokenNum,
		inPlainAutTokenNum:  inPlainAutTokenNum,
		outCTAutTokenNum:    outCTAutTokenNum,
		outPlainAutTokenNum: outPlainAutTokenNum,
		valueScripts:        valueScripts,
		witnessHash:         witnessHash,
		memo:                memo,
	}
}

func (script *BurnScript) Type() AutScriptType {
	return script.scriptType
}

func (script *BurnScript) Identifier() [AutIdentifierLength]byte {
	return script.ctAutIdentifier
}

func (script *BurnScript) Serialize() ([]byte, error) {
	var b bytes.Buffer
	var err error

	// todo: necessary to use a function?
	if err = writePrefix(&b, script.version, script.scriptType, script.ctAutIdentifier); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.inCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.inPlainAutTokenNum); err != nil {
		return nil, err
	}

	if err = b.WriteByte(script.outCTAutTokenNum); err != nil {
		return nil, err
	}
	if err = b.WriteByte(script.outPlainAutTokenNum); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeCTAUTTxoScripts(&b, script.valueScripts); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeWitnessHash(&b, script.witnessHash); err != nil {
		return nil, err
	}

	// todo: necessary to use a function?
	if err = writeMemo(&b, script.memo); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

// todo(ctaut): add a standalone sanity-check function, and call it at the end of deserialize
func (script *BurnScript) Deserialize(r io.Reader) error {
	var err error
	// todo: necessary to use a function?
	if script.version, script.ctAutIdentifier, script.scriptType, err = readPrefix(r, AutScriptTypeBurn); err != nil {
		return err
	}

	if script.inCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.inPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	if script.outCTAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}
	if script.outPlainAutTokenNum, err = ReadByte(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.valueScripts, err = readCTAUTTxoScript(r, int(script.outCTAutTokenNum), int(script.outPlainAutTokenNum)); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.witnessHash, err = readWitnessHash(r); err != nil {
		return err
	}

	// todo: necessary to use a function?
	if script.memo, err = readMemo(r); err != nil {
		return err
	}

	//	todo: sanity check can optimize the above checks
	if err = script.SanityCheck(); err != nil {
		return err
	}

	return nil
}
func (script *BurnScript) SanityCheck() error {
	// todo(ctaut): check version

	if script.scriptType != AutScriptTypeBurn {
		return errors.New("unexpected type for burn script")
	}

	if script.inCTAutTokenNum+script.inPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}
	if script.outCTAutTokenNum+script.outPlainAutTokenNum == 0 {
		return ErrInValidAUTTx
	}

	if int(script.outCTAutTokenNum) > MaxNumCTToken {
		return ErrInValidAUTTx
	}
	if len(script.valueScripts) != int(script.outCTAutTokenNum)+int(script.outPlainAutTokenNum) {
		return ErrInValidAUTTx
	}

	for i := 0; i < len(script.valueScripts); i++ {
		autTxo := &ctautwire.AutTxo{}
		err := autTxo.Deserialize(script.valueScripts[i])
		if err != nil {
			return err
		}
		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return ErrInValidAUTTx
		}
		if i < int(script.outCTAutTokenNum) {
			if autTxoType != abecryptox.AutTxoTypeHidden {
				return ErrInValidAUTTx
			}
		} else {
			if autTxoType != abecryptox.AutTxoTypePublic {
				return ErrInValidAUTTx
			}
		}
	}

	// todo: the burned one must be plainAut

	if len(script.memo) > MaxMemoLength {
		return ErrInValidAUTTx
	}

	return nil
}
func (script *BurnScript) NumConsumedTokens() int {
	return int(script.inCTAutTokenNum + script.inPlainAutTokenNum)
}
func (script *BurnScript) NumGeneratedTokens() int {
	return int(script.outCTAutTokenNum + script.outPlainAutTokenNum)
}

var _ AutScript = &BurnScript{}

var ErrNonAutTx = errors.New("not a AUT transaction")
var ErrInValidAUTTx = errors.New("not a valid AUT transaction")

// ParseAutScript try to deserialize CTAUT script from transaction memo
// todo: rename memo to TxMemo
// todo: why not use a MsgTxAbe as input?
func ParseAutScript(txVersion uint32, txHash chainhash.Hash, memo []byte) (script AutScript, err error) {
	if txVersion < wire.TxVersion_Height_464000_Aconcagua {
		return nil, nil
	}

	// could not be an AUT transaction
	if len(memo) < len(commonPrefix) {
		return nil, nil
	}
	if !bytes.Equal(memo[:len(commonPrefix)], []byte(commonPrefix)) {
		return nil, nil
	}

	if len(memo) == len(commonPrefix) {
		return nil, fmt.Errorf("the memo start with %s, but have no content", commonPrefix)
	}

	// todo(ctaut): why +1? "CTAUTSCRIPT" will result (nil, nil) or (nil, err)
	// todo(ctaut): only if ctaut-script's CommonPrefixLength is the the start position, it will be recognized as ctaut-script.
	// todo(ctaut): what "txMemo" should be shown at the front end?

	tmpReader := bytes.NewReader(memo[len(commonPrefix):])
	version, err := ReadVarInt(tmpReader)
	if err != nil {
		return nil, err
	}
	if version > math.MaxUint32 {
		return nil, ErrInValidAUTTx
	}
	// check the script version with the host version
	// todo: use the ScriptVersion and TxVersion rule.
	if uint32(version) != txVersion {
		return nil, ErrInValidAUTTx
	}

	scriptType, err := ReadByte(tmpReader)
	if err != nil {
		return nil, err
	}

	switch scriptType {
	case AutScriptTypeRegistration:
		script = &RegistrationScript{}
	case AutScriptTypeReRegistration:
		script = &ReRegistrationScript{}
	case AutScriptTypeMint:
		script = &MintScript{}
	case AutScriptTypeTransfer:
		script = &TransferScript{}
	case AutScriptTypeBurn:
		script = &BurnScript{}
	default:
		return nil, ErrInValidAUTTx
	}

	// reset the reader to deserialize the complete script
	reader := bytes.NewBuffer(memo)
	// todo: here use read; separate Write/Read and Serialize/Deserialize
	// todo: using Deserialize is also fine. [:]
	err = script.Deserialize(reader)
	if err != nil {
		return nil, err
	}

	// check the script version with the host version
	if script.Version() != txVersion {
		return nil, ErrInValidAUTTx
	}

	// populate the identifier for registration script
	if script.Type() == AutScriptTypeRegistration {
		ctAUTScript, ok := script.(*RegistrationScript)
		if !ok {
			return nil, ErrInValidAUTTx
		}
		ctAUTScript.ctAutIdentifier = txHash
	}

	return script, nil
}

// todo(ctaut): this is for database storage or only memeory? why has CoinAddress and ValueScript?
// todo(ctaut): define an interface? only a case needs coinAddress.
// CTAUTToken holds the main information of token in memory, it would be used to check all rules
type CTAUTToken struct {
	// inheritance from host transaction output
	Version uint32
	// used to track the host location on blockchain
	HostOutPoint HostOutPoint
	// For root token, value script would be nil,
	// For normal token, value script could be interpreted to either a public value or a hidden value
	// with abecryptox.ExtractAutTxoValue()
	// todo: serializedAutTxo, or AutTxo?
	ValueScript []byte // todo(ctaut): used to denote AUT value.
	// For all token, coin address would be used to indicate the ownership of token
	// For root token, it would be used match the claimed issuers to recognize operational permission
	CoinAddress []byte
}

// todo: what is this?
// todo: rename
type EnhancedAutScript struct {
	AutScript

	// Note that for following 2 fields:
	// - if the value is nil, it means that the tokens is not set
	// - if the value is empty slice, it means that the tokens is set but has no token
	consumedTokens  []*CTAUTToken
	generatedTokens []*CTAUTToken
}

func (script *EnhancedAutScript) ConsumedTokens() ([]*CTAUTToken, error) {
	if script.consumedTokens == nil {
		return nil, errors.New("consumed tokens not set")
	}

	return script.consumedTokens, nil
}
func (script *EnhancedAutScript) setConsumedTokens(consumedTokens []*CTAUTToken) error {
	if len(consumedTokens) != script.NumConsumedTokens() {
		return errors.New("mismatched number of consumed tokens")
	}

	script.consumedTokens = consumedTokens
	return nil
}

func (script *EnhancedAutScript) GeneratedTokens() ([]*CTAUTToken, error) {
	if script.generatedTokens == nil {
		return nil, errors.New("generated tokens not set")
	}

	return script.generatedTokens, nil
}
func (script *EnhancedAutScript) setGeneratedTokens(generatedTokens []*CTAUTToken) error {
	if len(generatedTokens) != script.NumGeneratedTokens() {
		return errors.New("mismatched number of consumed tokens")
	}

	script.generatedTokens = generatedTokens

	return nil
}

// todo: AutMetadata
func (script *EnhancedAutScript) Metadata() (*AutMetadata, error) {
	if script.Type() != AutScriptTypeRegistration {
		return nil, errors.New("metadata only available for registration script")
	}
	if script.generatedTokens == nil {
		return nil, errors.New("generated tokens not set")
	}

	registerScript, ok := script.AutScript.(*RegistrationScript)
	if !ok {
		return nil, errors.New("metadata only available for registration script")
	}

	rootTokenSet := map[HostOutPoint]struct{}{}
	for i := 0; i < len(script.generatedTokens); i++ {
		rootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}
	metadata := &AutMetadata{
		Version:                    registerScript.version,
		AutIdentifier:              registerScript.ctAutIdentifier,
		AutName:                    registerScript.ctAutName,
		AutSymbol:                  registerScript.ctAutSymbol,
		BaseUnitName:               registerScript.baseUnitName,
		SubUnitName:                registerScript.subUnitName,
		UnitScale:                  registerScript.unitScale,
		AutMemo:                    registerScript.ctAutMemo,
		PlannedTotalSupply:         registerScript.plannedTotalAmount,
		IssuerTokens:               registerScript.issuerTokens,
		MintThreshold:              registerScript.mintThreshold,
		ReregistrationThreshold:    registerScript.reregisterThreshold,
		ReregistrationExpireHeight: registerScript.reregistrationExpireHeight,

		MintedAmount:       0,
		BurnedAmount:       0,
		ActiveRootTokenSet: rootTokenSet,
	}
	return metadata, nil
}

// todo: AutMetadata
func (script *EnhancedAutScript) UpdateMetadata(metadata *AutMetadata) error {
	// assert
	if script.Type() != AutScriptTypeReRegistration {
		return errors.New("update metadata only available for re-registration script")
	}
	identifier := script.Identifier()
	if !bytes.Equal(identifier[:], metadata.AutIdentifier[:]) {
		return ErrInValidAUTTx
	}
	consumedTokens := script.consumedTokens
	for i := 0; i < len(consumedTokens); i++ {
		if _, ok := metadata.ActiveRootTokenSet[consumedTokens[i].HostOutPoint]; !ok {
			return fmt.Errorf("an re-registration AUT transaction try to update AUT "+
				"with non-existing/spent root token (%s,%d) for AUT identified by %s",
				consumedTokens[i].HostOutPoint.TxHash, consumedTokens[i].HostOutPoint.Index,
				metadata.AutIdentifier)
		}
		delete(metadata.ActiveRootTokenSet, consumedTokens[i].HostOutPoint)
	}

	reregisterScript, ok := script.AutScript.(*ReRegistrationScript)
	if !ok {
		return errors.New("update metadata only available for re-registration script")
	}
	metadata.AutMemo = reregisterScript.ctAutMemo
	// assert here?
	if metadata.MintedAmount > reregisterScript.plannedTotalAmount {
		return errors.New("re-registration transaction try to make planned amount less than minted amount")
	}
	metadata.PlannedTotalSupply = reregisterScript.plannedTotalAmount

	metadata.IssuerTokens = reregisterScript.issuerTokens
	metadata.MintThreshold = reregisterScript.mintThreshold
	metadata.ReregistrationThreshold = reregisterScript.reregisterThreshold
	metadata.ReregistrationExpireHeight = reregisterScript.reregistrationExpireHeight

	// remove previous root tokens
	metadata.ActiveRootTokenSet = make(map[HostOutPoint]struct{}, len(script.generatedTokens))
	for i := 0; i < len(script.generatedTokens); i++ {
		metadata.ActiveRootTokenSet[script.generatedTokens[i].HostOutPoint] = struct{}{}
	}

	return nil
}

// ExtractAutScript try to deserialize CTAUT script from transaction memo
// if success, it would :
// - extract the well-formed script from memo with sanity check:
//   - no conflict configuration
//   - no token parasitized in invalid host output
//
// - populate the generated tokens by CTAUT script by populateGeneratedTokens
//
// Note that the legality of consumed tokens and the effect of script MUST be checked
// with the help of instance on blockchain.
// - legality of host transaction input
//   - no double/duplicate spending token
//
// - legality of witness
// - effect on the instance
//   - no overflow
//
// todo: CTAUT to Aut?
// todo: what is the relation with Parse
// todo: rename to Aut
func ExtractAutScript(tx *wire.MsgTxAbe) (enhancedScript *EnhancedAutScript, err error) {
	if tx.Version < wire.TxVersion_Height_464000_Aconcagua {
		return nil, nil
	}
	// parse script from memo and check well-formedness
	autScript, err := ParseAutScript(tx.Version, tx.TxHash(), tx.TxMemo)
	if err != nil {
		return nil, err
	}
	if autScript == nil {
		return nil, nil
	}

	// populate the generated tokens with host transaction outputs
	enhancedScript = &EnhancedAutScript{
		AutScript:       autScript,
		consumedTokens:  nil,
		generatedTokens: nil,
	}
	tokens, err := GetGeneratedAutTokens(autScript, tx.TxHash(), tx.TxOuts)
	if err != nil {
		return nil, err
	}
	err = enhancedScript.setGeneratedTokens(tokens)
	if err != nil {
		return nil, err
	}

	switch script := autScript.(type) {
	case *RegistrationScript:
		// for inputs, there is no rules

		// for outputs, the claimed issuer tokens must match the generated tokens exactly
		// - all issuer tokens must appear
		// - no unclaimed issuer token appear
		if err = matchIssuerTokens(script.issuerTokens, tokens); err != nil {
			return nil, err
		}
	case *ReRegistrationScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the re-register threshold is meet
		// Above checks have to be delayed until the instance could be seen

		// for outputs, the claimed issuer tokens must match the outputs exactly
		if err = matchIssuerTokens(script.issuerTokens, tokens); err != nil {
			return nil, err
		}
	case *MintScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the mint threshold is meet
		// 3. check the balance proof
		// 4. check whether minted amount conflict with planned total amount
		// Above checks have to be delayed until the instance could be seen

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}

	case *TransferScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the balance proof
		// Above checks have to be delayed until the instance could be seen

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}

	case *BurnScript:
		// for inputs, note that here is no enough information to
		// 1. check the legality of token
		// 2. check the balance proof
		// Above checks have to be delayed until the instance could be seen

		// for outputs, check the legality of burned token (a.k.a last generated token)
		// Above ParseCTAUTScript() ensures the length of valueScripts is not less than 1
		autTxo := &ctautwire.AutTxo{}
		err = autTxo.Deserialize(script.valueScripts[len(script.valueScripts)-1])
		if err != nil {
			return nil, err
		}
		autTxoType, err := abecryptox.GetAutTxoType(autTxo)
		if err != nil {
			return nil, fmt.Errorf("fail to get last aut txo type from burn script: %v")
		}
		// assert the last aut txo is public
		if autTxoType != abecryptox.AutTxoTypePublic {
			return nil, fmt.Errorf("last aut txo type must not public")
		}

		//witnessHash := chainhash.HashH(tx.AutWitness)
		//if !witnessHash.IsEqual(&script.witnessHash) {
		//	return nil, fmt.Errorf("mismatch witness for script")
		//}
	default:
		return nil, ErrInValidAUTTx
	}

	return enhancedScript, nil
}

// PresetHostOutpointForCTAUT would preset the host outpoint for consumed tokens with the help of
// host transaction and ring
// todo: use the correcy HostOutPoint
func PresetHostOutpointForCTAUT(script *EnhancedAutScript, msgTx *wire.MsgTxAbe,
	lookupHostOutput func(ringHash chainhash.Hash) (*wire.TxOutAbe, error),
) error {
	if script == nil || script.AutScript == nil {
		return nil
	}
	if script.Type() == AutScriptTypeRegistration {
		return script.setConsumedTokens([]*CTAUTToken{})
	}
	txHash := msgTx.TxHash()

	hostedTxIns := msgTx.TxIns
	startIndex := 0
	for ; startIndex < len(hostedTxIns); startIndex++ {
		ringHash := hostedTxIns[startIndex].PreviousOutPointRing.Hash()
		txOut, err := lookupHostOutput(ringHash)
		if err != nil {
			return err
		}

		privacyLevel, err := abecryptox.GetTxoPrivacyLevel(txOut)
		if err != nil {
			return err
		}

		// skip fully-privacy area
		if privacyLevel == abecryptoxkey.PrivacyLevelRINGCTPre ||
			privacyLevel == abecryptoxkey.PrivacyLevelRINGCT {
			continue
		}

		if privacyLevel != abecryptoxkey.PrivacyLevelPSEUDONYMCT {
			return fmt.Errorf("expect privacy level %d but got %d",
				abecryptoxkey.PrivacyLevelPSEUDONYMCT, privacyLevel)
		}
		break
	}

	numInCoins := script.NumConsumedTokens()
	if startIndex+numInCoins > len(hostedTxIns) {
		return fmt.Errorf("claim %d (root) coins but only remain %d outputs",
			numInCoins, len(hostedTxIns)-startIndex)
	}

	consumedTokens := make([]*CTAUTToken, numInCoins)
	for i := 0; i < len(consumedTokens); i++ {
		hostIndex := startIndex + i

		// sanity-check
		ringHash := hostedTxIns[hostIndex].PreviousOutPointRing.Hash()
		txOut, err := lookupHostOutput(ringHash)
		if err != nil {
			return err
		}

		privacyLevel, err := abecryptox.GetTxoPrivacyLevel(txOut)
		if err != nil {
			return err
		}
		if privacyLevel != abecryptoxkey.PrivacyLevelPSEUDONYMCT {
			return fmt.Errorf("expect privacy level %d but got %d",
				abecryptoxkey.PrivacyLevelPSEUDONYMCT, privacyLevel)
		}

		// fill out with the first item in ring
		ringIdx := 0
		outpoint := HostOutPoint{
			TxHash: hostedTxIns[hostIndex].PreviousOutPointRing.OutPoints[ringIdx].TxHash,
			Index:  hostedTxIns[hostIndex].PreviousOutPointRing.OutPoints[ringIdx].Index,
		}

		coinAddress, err := CheckHostTxoParasiticity(outpoint.TxHash, outpoint.Index, txOut)
		if err != nil {
			return fmt.Errorf("transaction %s try to consume UTXO at Ring %s is not a valid output", txHash,
				hostedTxIns[hostIndex].PreviousOutPointRing.Hash())
		}

		err = abecryptox.AutRuleCheckOnTxInputVersion(hostedTxIns[hostIndex].PreviousOutPointRing.Version, msgTx.Version)
		if err != nil {
			return fmt.Errorf("transaction %s try to consume CT-AUT token %s with version %d, but tx version is %d",
				txHash, outpoint,
				hostedTxIns[hostIndex].PreviousOutPointRing.Version, msgTx.Version)
		}

		consumedTokens[i] = &CTAUTToken{
			HostOutPoint: outpoint,
			Version:      hostedTxIns[hostIndex].PreviousOutPointRing.Version,
			ValueScript:  nil,         // will be populated later with CTAUTViewpoint
			CoinAddress:  coinAddress, // required by root coin while optional for coin
		}
	}
	return script.setConsumedTokens(consumedTokens)
}
